/**
 * Palavras da Digitação Ligeira (pt-BR). Curtas o bastante para digitar rápido no celular e
 * variadas: algumas com acento (para a regra "sem acentos") e todas com consoante e com letra
 * diferente de "a" (para "sem vogais" e "sem a letra A" nunca ficarem vazias).
 */
export const WORDS: readonly string[] = [
  'banana',
  'cidade',
  'janela',
  'estrela',
  'pipoca',
  'sorvete',
  'chuveiro',
  'bicicleta',
  'cachorro',
  'girafa',
  'montanha',
  'foguete',
  'tesouro',
  'piscina',
  'biscoito',
  'pirata',
  'floresta',
  'vulcão',
  'coração',
  'música',
  'café',
  'avião',
  'maçã',
  'pão',
  'feijão',
  'limão',
  'balão',
  'caminhão',
  'irmão',
  'jardim',
  'cadeira',
  'televisão',
  'fantasma',
  'dragão',
  'lâmpada',
  'ônibus',
  'pássaro',
  'árvore',
  'açúcar',
  'sábado',
  'médico',
  'último',
  'rápido',
  'lógica',
  'câmera',
  'técnico',
  'saída',
  'água',
  'fácil',
  'difícil',
  'brinquedo',
  'carrinho',
  'palhaço',
  'cenoura',
  'tomate',
  'abacaxi',
  'morango',
  'melancia',
  'chocolate',
  'pudim',
  'sanduíche',
  'garrafa',
  'mochila',
  'caderno',
  'borracha',
  'lápis',
  'tesoura',
  'espelho',
  'travesseiro',
  'cobertor',
  'sofá',
  'relógio',
  'telefone',
  'computador',
  'teclado',
  'mouse',
  'internet',
  'mensagem',
  'amizade',
  'festa',
  'presente',
  'aventura',
  'segredo',
  'mistério',
  'tempestade',
  'trovão',
  'relâmpago',
  'cachoeira',
  'oceano',
  'tartaruga',
  'golfinho',
  'elefante',
  'macaco',
  'coruja',
  'borboleta',
];

/**
 * Frases curtas (até 30 caracteres) para digitar. Todas têm a letra "a" e várias têm acento, para
 * as regras "sem a letra A" e "sem acentos" nunca ficarem vazias nem triviais.
 */
export const PHRASES: readonly string[] = [
  'bom dia pessoal',
  'pão com manteiga',
  'vamos jogar de novo',
  'o gato subiu no telhado',
  'chuva de verão',
  'café com leite',
  'amanhã eu chego cedo',
  'isso é muito legal',
  'fim de semana na praia',
  'o tempo não para',
  'sorvete de chocolate',
  'devagar e sempre',
  'cada coisa em seu lugar',
  'mais vale tarde do que nunca',
  'água mole em pedra dura',
  'um dia de cada vez',
  'foguete não tem ré',
  'tudo azul por aqui',
  'ninguém é de ferro',
  'rir é o melhor remédio',
  'de grão em grão',
  'quem ri por último',
  'ela abriu a janela',
  'o pássaro cantou cedo',
  'a lua está linda hoje',
  'preciso de uma pausa',
  'que a sorte esteja com você',
  'não vale correr na frente',
  'agora é a minha vez',
  'o jogo já vai começar',
  'cuidado com a pegadinha',
  'leia com muita atenção',
  'acertei na última hora',
  'todo mundo na mesma sala',
];
