import { color, type PaletteColor } from './palette-types';

/** Roxos, magentas e rosas. */
export const PALETTE_3: PaletteColor[] = [
  color('Lavanda', 260, 28, 96, [
    'Roxo bem clarinho, cor da flor de lavanda e do sachê da gaveta de roupa.',
    'Quase branco com um suspiro de roxo: calmo, macio e perfumado.',
    'Brilho altíssimo e saturação baixa: um roxo de pijama de domingo.',
    'Mais azulado que o lilás e bem mais suave que o violeta.',
    'Cor de sabonete caro que ninguém usa, só deixa de enfeite.',
    'A cor do campo de flores nas fotos de viagem pela França.',
    'Cor de vela aromática com nome de spa.',
    'Se o sono tivesse uma cor, seria essa.',
    'Roxo de quem prefere não aparecer e consegue.',
  ]),
  color('Lilás', 280, 35, 90, [
    'Roxo claro com um toque rosado, cor de flor de primavera.',
    'Brilho alto e saturação média-baixa: roxo gostoso de olhar.',
    'Cor de gominha de uva que perdeu um pouco do sabor.',
    'Mais rosado que a lavanda e mais claro que a orquídea.',
    'A cor das unhas de quem ama esmalte pastel.',
    'Cor de ursinho de pelúcia vendido em shopping.',
    'Lilás de papel de carta de adolescente dos anos noventa.',
    'Suave, doce e levemente nostálgico.',
    'Se o roxo fosse suco, seria o de uva misturado com muita água.',
  ]),
  color('Glicínia', 255, 35, 85, [
    'Roxo azulado e suave, cor da flor de glicínia caindo em cachos.',
    'Mais azul que o lilás e mais acinzentado que a lavanda.',
    'Brilho alto e saturação média-baixa: delicado como pétala.',
    'Cor de pergolado de casamento ao ar livre.',
    'Roxo de céu no fim da tarde, quando o laranja já foi embora.',
    'A cor de cortina de quarto de casa de campo.',
    'Frio e suave, quase um azul que está pensando em ser roxo.',
    'Cor de camiseta que você ganha e nunca sabe como combinar.',
    'Parece uma névoa de manhã com um pouco de tinta.',
  ]),
  color('Violeta', 265, 80, 85, [
    'Roxo vivo e profundo, o violeta do arco-íris, entre o azul e o roxo.',
    'Saturação alta e brilho alto: forte, mas sem escuridão.',
    'Cor da flor violeta e de um suco de uva concentrado.',
    'Mais azulado que o roxo uva e mais vivo que a lavanda.',
    'Cor de luz negra de balada, antes de ficar escura.',
    'Violeta de manto de rei em peça de teatro.',
    'A última faixa de cor do arco-íris, a que ninguém cita de cabeça.',
    'Cor de gominha de uva que foi comprada pelo nome, não pelo sabor.',
    'Misteriosa, mas sem fazer drama.',
  ]),
  color('Roxo Uva', 280, 65, 55, [
    'A cor da uva roxa madura, da casca ao suco.',
    'Roxo médio e escuro, com um pé no vinho e outro no azul.',
    'Cor de refrigerante de uva que mancha a camisa branca.',
    'Brilho médio-baixo e saturação média-alta: roxo de verdade, sem pastel.',
    'A cor de geleia de uva na torrada do café da manhã.',
    'Mais escuro que o violeta, mais claro que a berinjela.',
    'Cor de língua de quem comeu muita amora.',
    'Roxo de camiseta de time que não é seu mas você respeita.',
    'Escuro, doce e meio pegajoso: é uva.',
  ]),
  color('Roxo Berinjela', 295, 50, 32, [
    'A casca da berinjela: roxo tão escuro que parece quase preto.',
    'Brilho baixíssimo e saturação média: sombrio com um fundo de vinho.',
    'Cor de sofá de veludo de sala de gente muito séria.',
    'Mais escuro que o roxo uva e mais avermelhado que o azul noite.',
    'Roxo de noite chuvosa vista da janela.',
    'Cor de capa de bruxo de filme que se leva muito a sério.',
    'Quase preto, mas com uma alma roxa escondida.',
    'Cor de esmalte que as pessoas chamam de preto-roxo.',
    'Se a meia-noite tivesse um tom, seria um pouquinho disso.',
  ]),
  color('Ameixa', 308, 55, 52, [
    'A cor da ameixa madura: roxo avermelhado, escuro e meio opaco.',
    'Entre o roxo e o vinho, com mais rosa do que parece.',
    'Brilho médio-baixo e saturação média: sofisticado e discreto.',
    'Cor de batom que a tia usa em foto de formatura.',
    'Mais avermelhado que a berinjela e mais escuro que a orquídea.',
    'Cor de geleia que só aparece em loja de produtos naturais.',
    'A cor da calda de ameixa do pudim de Natal.',
    'Roxo quente, com cara de outono.',
    'Parece vinho misturado com uva e com um pouco de ideia.',
  ]),
  color('Índigo', 272, 100, 52, [
    'Roxo muito saturado e escuro, a cor do sétimo degrau do arco-íris, o índigo.',
    'Entre o azul e o violeta, mais fundo e concentrado.',
    'Saturação no máximo e brilho médio: nada de pastel, nada de diluição.',
    'Cor de tinta de lula em desenho animado.',
    'Cor da noite quando já não é azul, mas ainda não é preto.',
    'A cor do tecido de uma capa de feiticeiro azul-arroxeado.',
    'Mais violeta que o anil e mais escuro que o roxo real.',
    'Cor de aurora boreal no cantinho mais escuro do céu.',
    'Intenso, fundo e meio místico.',
  ]),
  color('Roxo Real', 270, 85, 65, [
    'Roxo forte e nobre, de manto de rei antigo.',
    'Saturação alta e brilho médio: roxo cheio, sem cinza.',
    'Cor de capa de livro de fantasia que a prateleira inteira ama.',
    'Mais escuro que o violeta e mais vivo que o roxo uva.',
    'Cor de pacote de chocolate de marca famosa.',
    'Cor da faixa de campeão de campeonato local.',
    'Roxo de brasão de castelo, daqueles bordados à mão.',
    'Intenso e elegante, mas ainda bem acordado.',
    'Se o roxo precisasse de uma coroa, seria esse.',
  ]),
  color('Violeta Elétrico', 275, 90, 100, [
    'Roxo vibrante que parece aceso por dentro.',
    'Brilho no máximo e saturação quase no limite: não tem como ignorar.',
    'Cor de luz de LED roxa de loja de games.',
    'Mais vivo que o violeta e mais claro que o roxo real.',
    'Cor de poção mágica de desenho animado, daquelas que borbulham.',
    'Roxo de neon de balada que promete uma noite longa.',
    'Violeta que parece ter tomado energético.',
    'Tem mais energia que qualquer outro roxo da paleta.',
    'Cor de fundo de apresentação de empresa de tecnologia.',
  ]),
  color('Orquídea', 300, 45, 90, [
    'Roxo rosado e delicado, cor da pétala da orquídea.',
    'Entre o lilás e o rosa, com mais roxo do que rosa.',
    'Brilho alto e saturação média: flor de vaso de sala de espera cara.',
    'A cor da orquídea que a vizinha cuida melhor que o próprio cachorro.',
    'Mais quente que o lilás e mais frio que o rosa chiclete.',
    'Cor de gloss de brilho que aparece em todos os aniversários.',
    'Rosa-lilás de papel de presente caprichado.',
    'Delicada, mas com personalidade.',
    'Parece uma flor que sabe exatamente o quanto é bonita.',
  ]),
  color('Lilás Pastel', 270, 18, 100, [
    'Roxo tão claro que parece um branco com vontade de cor.',
    'Brilho máximo e saturação baixíssima: um lilás de nuvem de desenho.',
    'Cor de glacê de bolo de aniversário infantil.',
    'Mais claro que a lavanda e muito mais suave que o lilás.',
    'Cor de ursinho de bebê que ainda não tem nome.',
    'A cor de um filtro de foto que diz "estética" no nome.',
    'Quase não aparece, mas dá um toque de roxo em tudo.',
    'Doce, fofo e fácil de combinar.',
    'Cor de unha de manicure que nunca descasca.',
  ]),
  color('Magenta', 300, 100, 90, [
    'Roxo com rosa na mesma força: o magenta da impressora.',
    'Saturação no máximo e brilho alto: não existe cor mais berrante.',
    'Cor de tinta de cartucho que sempre acaba antes das outras.',
    'Exatamente no meio entre o vermelho e o azul no círculo de cores.',
    'Cor de flor de cacto no deserto, que só aparece uma vez por ano.',
    'Mais roxo que o fúcsia e mais forte que a orquídea.',
    'Cor de capa de revista de moda dos anos oitenta.',
    'Se o roxo e o rosa brigassem, o resultado seria essa cor.',
    'Vibrante, quente e totalmente sem filtro.',
  ]),
  color('Magenta Escuro', 315, 90, 55, [
    'Roxo avermelhado e profundo, como suco de beterraba com uva.',
    'Brilho médio-baixo e saturação alta: magenta que foi dormir tarde.',
    'Cor de veludo de poltrona de teatro de ópera.',
    'Mais escuro que o magenta e mais roxo que a beterraba.',
    'Cor de vinho misturado com pitada de rosa.',
    'Magenta fechado, de cortina de teatro em estreia.',
    'Quase uma ameixa, só que muito mais saturada.',
    'Cor de batom ousado em evento de gala.',
    'Intenso e dramático, sem pedir desculpas.',
  ]),
  color('Fúcsia', 320, 90, 95, [
    'Rosa-roxo bem forte, cor da flor de brinco-de-princesa.',
    'Brilho altíssimo e saturação alta: aceso como lâmpada rosa.',
    'Cor de blusa que alguém sempre usa em dia de festa junina.',
    'Mais rosa que o magenta e mais roxo que o rosa choque.',
    'A cor de bala de goma de cereja que deixa a língua pintada.',
    'Rosa vibrante que não admite concorrência.',
    'Cor de cabelo de personagem de anime.',
    'Chamativo, alegre e bem tropical.',
    'Cor de flor que o beija-flor adora.',
  ]),
  color('Rosa Choque', 328, 92, 100, [
    'Rosa mais aceso que existe: choque de tão forte.',
    'Brilho e saturação nas alturas, sem nenhum tom de cinza.',
    'Cor de boneca que toda criança dos anos noventa queria ter.',
    'Mais vermelho que o fúcsia e muito mais quente que o rosa chiclete.',
    'Cor de ensaio de neon de filme sobre o verão.',
    'Rosa de roupa de academia dos anos oitenta.',
    'O rosa que grita para o fundo da sala.',
    'Cor de chiclete de cereja mascado por cinco minutos.',
    'Cor de laço de presente que ninguém ignora.',
  ]),
  color('Rosa Chiclete', 335, 45, 100, [
    'Rosa claro e alegre, cor de chiclete de bola de verdade.',
    'Brilho máximo e saturação média: rosa doce sem exagero.',
    'Cor de bola de chiclete prestes a estourar na cara de alguém.',
    'Mais claro que o rosa choque e mais forte que o algodão-doce.',
    'Cor de sorvete de morango com leite condensado.',
    'Rosa de pelúcia de parque de diversões.',
    'Rosa doce que lembra balcão de confeitaria.',
    'Cor de fita de cabelo que combina com tudo.',
    'Se fosse sabor, seria bala de tutti-frutti.',
  ]),
  color('Rosa Algodão-Doce', 330, 22, 100, [
    'Rosa claríssimo e fofo, cor de algodão-doce de parque.',
    'Brilho máximo e saturação baixa: parece nuvem açucarada.',
    'Cor de bolinha de confeito no bolo de aniversário.',
    'Mais clara que o rosa chiclete e mais forte que o rosa bebê.',
    'Rosa de babado de vestido de princesa.',
    'Cor de pelúcia de coelhinho de Páscoa.',
    'Doce demais para ser séria, bonita demais para ser ignorada.',
    'Rosa que derrete na primeira chuva.',
    'Cor de pacote de marshmallow aberto.',
  ]),
  color('Rosa Bebê', 345, 15, 100, [
    'Rosa quase branco, delicadíssimo, de enxoval de recém-nascido.',
    'Brilho máximo e saturação baixíssima: só um sopro de rosa.',
    'Cor de babador e de sapatinho de tricô.',
    'Mais claro que o algodão-doce e bem mais calmo.',
    'Cor de bochecha de bebê recém-banhado.',
    'Rosa de papel de embrulho de maternidade.',
    'Quase não é rosa, mas ninguém duvida.',
    'Suave como cobertor de berço.',
    'Parece o rosa depois de lavar três vezes na água quente.',
  ]),
  color('Rosa Antigo', 350, 30, 75, [
    'Rosa acinzentado e envelhecido, como cortina de casa de campo.',
    'Brilho médio-alto e saturação baixa: rosa com ar de coisa vintage.',
    'Cor de fotografia antiga que desbotou no álbum da avó.',
    'Mais escuro e mais apagado que o rosa chiclete.',
    'Rosa de poltrona de consultório de médico antigo.',
    'Cor de chá de rosas servido em xícara de porcelana.',
    'Tom terroso, discreto e muito elegante.',
    'Cor de laço de sapatilha de balé usada muitas vezes.',
    'Se o rosa se aposentasse, ficaria assim.',
  ]),
  color('Rosa Quartzo', 340, 14, 90, [
    'Rosa fosco e suave, cor de pedra de quartzo rosa polida.',
    'Brilho alto e saturação baixíssima: quase cinza, mas quente.',
    'Cor de esfoliante de rosto vendido em loja natural.',
    'Mais acinzentado que o rosa bebê e menos doce.',
    'Cor de parede de salão de beleza de bairro chique.',
    'A pedra que as pessoas dizem que traz amor e traz só um adorno.',
    'Rosa de pele clara com um toque de blush.',
    'Cor de embalagem de produto caro que se diz minimalista.',
    'Sutil, neutro e silenciosamente bonito.',
  ]),
  color('Rosa Flamingo', 345, 55, 100, [
    'Rosa vivo de penas de flamingo, entre o salmão e o chiclete.',
    'Brilho máximo e saturação média: alegre e tropical.',
    'Cor de boia gigante em forma de ave na piscina.',
    'Mais quente que o chiclete e mais rosado que o coral.',
    'Cor de drinque de verão com guarda-chuvinha.',
    'Rosa de camisa estampada de férias em Miami.',
    'Cor de bochecha corada depois de cantar em voz alta.',
    'Fica entre o rosa e o laranja claro, mas ganha para o rosa.',
    'Cor de pôr do sol em praia que só aparece em foto.',
  ]),
  color('Rosa Peônia', 345, 65, 95, [
    'Rosa forte e macio de pétala de peônia, cheio de camadas.',
    'Brilho alto e saturação média-alta: flor de buquê de casamento.',
    'Mais intenso que o flamingo e mais suave que o choque.',
    'Cor de vestido de madrinha que ninguém sabe usar de novo.',
    'Rosa de lábios de personagem de pintura renascentista.',
    'Cor de torta de framboesa com creme.',
    'Rosa de jardim cuidado com muito carinho e muita regra.',
    'Rosado e vivo, mas sem gritar.',
    'Se uma flor fosse uma sobremesa, seria essa.',
  ]),
  color('Beterraba', 335, 80, 45, [
    'Roxo avermelhado e escuro do suco de beterraba que mancha tudo.',
    'Brilho baixo e saturação alta: um rosa que foi cozinhado por horas.',
    'Cor de caldo de feijão misturado com açaí.',
    'Mais escuro que o framboesa e mais rosado que o vinho.',
    'Cor da mão de quem descascou beterraba sem luvas.',
    'Cor de borra de vinho que sobrou na taça de ontem.',
    'Rosa escuro e terroso, com cara de raiz recém-arrancada.',
    'Intenso, doce e meio dramático.',
    'Cor de salada que faz a travessa inteira parecer instagramável.',
  ]),
];
