import { color, colorHex, type PaletteColor } from './palette-types';

/** Quentes: vermelhos, laranjas e amarelos. */
export const PALETTE_1: PaletteColor[] = [
  color('Vermelho Tomate', 7, 85, 90, [
    'Vermelho vivo com um fiozinho de laranja, a cor do tomate maduro cortado ao meio.',
    'Mais alegre que o vermelho de sangue e mais quente que o vermelho de cereja.',
    'Cor do molho de tomate fresco, antes de apurar na panela.',
    'Tomate-cereja saindo da geladeira: vermelho forte, claro e lustroso.',
    'Se o ketchup tivesse vergonha, ficaria dessa cor.',
  ]),
  color('Vermelho Sangue', 355, 90, 65, [
    'Vermelho bem escuro e fechado, quase marrom de tão pesado, mas ainda vermelho.',
    'A cor do sangue que escorre em filme de terror.',
    'Cor de cortina de teatro antiga, daquelas de veludo pesado.',
    'Mais escuro que um tomate e mais vivo que um vinho.',
    'Cor da capa de vampiro que se leva a sério.',
  ]),
  color('Carmim', 348, 90, 75, [
    'Vermelho forte e elegante com um toque de rosa, sem nada de laranja.',
    'A cor do batom de quem chega por último e rouba a cena.',
    'Cor de tapete vermelho de cerimônia, mais fundo que o vermelho de tomate.',
    'Entre o vermelho de sangue e a cereja: escuro, mas ainda vivo.',
    'Vermelho chique, daqueles que pedem um terno preto ao lado.',
  ]),
  color('Cereja', 345, 85, 70, [
    'Vermelho meio arroxeado, escuro e lustroso como uma cereja envernizada.',
    'A cor da cereja do bolo, aquela que ninguém quer dividir.',
    'Mais frio e mais escuro que o tomate, quase vinho, mas ainda fruta.',
    'Cor da calda de cereja derretida em cima do sorvete.',
    'Vermelho com um pé no roxo, tipo batom de festa.',
  ]),
  color('Morango', 350, 75, 92, [
    'Vermelho claro e alegre, com um toque rosado, de morango fresco.',
    'A cor da calda de morango em cima do sorvete de baunilha.',
    'Mais claro e mais rosado que o tomate, sem nada de escuro.',
    'Cor de gominha de morango que você jura que é saudável.',
    'Vermelho de iogurte de morango: doce, leve e sem drama.',
  ]),
  color('Vinho', 345, 80, 45, [
    'Vermelho bem escuro com um toque de roxo, a cor do vinho tinto na taça.',
    'Escuro e sério, o oposto de um vermelho de bala.',
    'Cor de poltrona de veludo de escritório de advogado.',
    'Mais escuro que a cereja, mais roxo que o tijolo.',
    'Se o carmim ficasse de luto, seria isso.',
  ]),
  color('Tijolo', 10, 65, 70, [
    'Vermelho alaranjado e meio apagado, a cor do tijolo de obra.',
    'Cor de telhado e de parede de casa de fazenda sem reboco.',
    'Vermelho terroso e opaco, nada lustroso nem vibrante.',
    'Mais queimado que o tomate, mais claro que a ferrugem.',
    'Cor de quadra de saibro depois de uma partida de tênis.',
  ]),
  color('Ferrugem', 18, 80, 65, [
    'Laranja escuro puxando para o marrom, a cor do ferro velho enferrujado.',
    'Cor de portão que ninguém pinta há vinte anos.',
    'Mais marrom que a abóbora e mais laranja que o tijolo.',
    'Cor de folha de outono que acabou de secar.',
    'Cor de cano velho de quintal depois de muita chuva.',
  ]),
  color('Coral', 10, 60, 100, [
    'Laranja rosado bem claro e alegre, cor de coral de praia de cartão-postal.',
    'Entre o salmão e o vermelho: mais vivo que o salmão, mais claro que o tomate.',
    'Cor de batom de verão e de biquíni de loja de praia.',
    'Rosa alaranjado que combina com pele bronzeada.',
    'Cor de camarão cozido, na versão mais simpática.',
  ]),
  color('Salmão', 10, 45, 98, [
    'Rosa alaranjado clarinho e suave, igual ao filé de salmão cru.',
    'Mais pálido que o coral e mais quente que o rosa chiclete.',
    'Cor de sashimi bem fresco no prato branco.',
    'Rosa-pêssego quente, longe de qualquer vermelho forte.',
    'Cor de camiseta polo que o seu tio diz que é "rosa-claro".',
  ]),
  color('Laranja Cenoura', 28, 90, 95, [
    'Laranja forte e vivo, a cor da cenoura recém-arrancada da horta.',
    'Laranja de verdade, nem avermelhado nem amarelado.',
    'Cor de cone de trânsito e de colete de obra.',
    'Mais amarelado que a abóbora e mais escuro que a tangerina.',
    'A cor do suco de laranja com cenoura que a mãe empurrava de manhã.',
  ]),
  color('Laranja Tangerina', 24, 95, 100, [
    'Laranja muito vivo e luminoso, a casca da tangerina descascada.',
    'Mais claro e mais aceso que a cenoura, cor de gominho de fruta.',
    'Cor de refrigerante de laranja gelado.',
    'Laranja de bola de basquete, bem alegre e sem sombra.',
    'Cor de pôr do sol de verão em foto sem filtro.',
  ]),
  color('Abóbora', 22, 85, 85, [
    'Laranja forte e quente, a cor da abóbora assada de Halloween.',
    'Mais fechado que a tangerina e menos marrom que a ferrugem.',
    'Cor de folha de árvore no começo do outono.',
    'Laranja de sopa de abóbora cremosa no prato fundo.',
    'Cor de lanterna de festa de bruxas, laranja com cara de outono.',
  ]),
  color('Damasco', 30, 45, 98, [
    'Laranja clarinho e suave, quase um pêssego, a cor da fruta damasco.',
    'Mais claro que a tangerina, bem pastel, sem nenhum tom forte.',
    'Cor de parede de quarto de bebê com jeito de tarde de sol.',
    'Laranja aguado, tipo suco de laranja misturado com leite.',
    'Cor de paçoca de doce de abóbora com leite.',
  ]),
  color('Pêssego', 25, 35, 100, [
    'Laranja bem clarinho com um toque de rosa, a cor da polpa do pêssego.',
    'Quase da cor de uma pele clara, só um pouquinho mais alaranjada.',
    'Mais pálido que o damasco e mais amarelado que o salmão.',
    'Cor de sorvete de pêssego derretendo na casquinha.',
    'Cor de esmalte discreto de quem não gosta de ousar.',
  ]),
  color('Âmbar', 40, 95, 90, [
    'Laranja dourado e forte, cor de pedra de âmbar contra a luz.',
    'Entre o laranja e o amarelo ouro, mais quente que o mel.',
    'Cor de farol de carro antigo piscando.',
    'Cor de cerveja clara no copo, com a luz batendo atrás.',
    'Cor do semáforo na hora do amarelo, quase laranja.',
  ]),
  color('Mel', 42, 85, 90, [
    'Amarelo alaranjado e dourado, a cor do mel escorrendo da colher.',
    'Mais quente e mais fundo que o amarelo ovo, quase caramelo claro.',
    'Cor do mel no pote de vidro, contra a luz da janela.',
    'Dourado doce e grosso, pegajoso só de olhar.',
    'A cor das listras de uma abelha, só que sem o preto.',
  ]),
  color('Mostarda', 48, 90, 80, [
    'Amarelo queimado e meio esverdeado, a cor da mostarda do cachorro-quente.',
    'Amarelo sério e sem alegria, longe do amarelo de banana.',
    'Cor de poltrona retrô dos anos setenta.',
    'Mais escuro que o ouro e mais amarelado que o mel.',
    'Cor de suéter de tio que acha que está na moda.',
  ]),
  color('Amarelo Gema', 42, 88, 98, [
    'Amarelo bem forte com um toque de laranja, a gema do ovo mole.',
    'Cor de gema de ovo caipira, mais intensa que a do mercado.',
    'Mais alaranjado que o amarelo banana, mais claro que o âmbar.',
    'Amarelo de ovo frito na frigideira, com a gema ainda de pé.',
    'Cor de gema de ovo no bolo de fubá antes de assar.',
  ]),
  color('Amarelo Limão', 55, 85, 98, [
    'Amarelo bem vivo com um toque de verde, a casca do limão-siciliano.',
    'Amarelo ácido e fresco, longe de qualquer tom de laranja.',
    'Cor do marca-texto amarelo que acaba antes de todos os outros.',
    'Amarelo de bala azeda que faz careta antes de mastigar.',
    'Mais esverdeado que a banana e mais forte que o creme.',
  ]),
  color('Amarelo Banana', 50, 60, 100, [
    'Amarelo claro e suave, a casca da banana bem madura.',
    'Mais pálido que o canário e mais amarelinho que o creme.',
    'Cor de pudim de baunilha com cobertura de caramelo claro.',
    'Amarelo de pintinho recém-nascido, macio e sem exagero.',
    'Cor de emoji de rosto feliz, versão mais calma.',
  ]),
  color('Amarelo Canário', 54, 80, 100, [
    'Amarelo vivo e puro, sem laranja nem verde, a cor do pássaro canário.',
    'Amarelo de pato de borracha na banheira.',
    'Cor de capa de chuva de criança que ninguém perde de vista.',
    'Mais forte que o amarelo banana, mais limpo que a mostarda.',
    'Cor de lápis amarelo novinho que ninguém apontou ainda.',
  ]),
  color('Amarelo Milho', 48, 75, 100, [
    'Amarelo quente e dourado de espiga de milho cozido.',
    'Mais alaranjado que o canário e mais claro que o ouro.',
    'Cor de pipoca amanteigada saindo do micro-ondas.',
    'Amarelo de grãozinho de milho brilhando na água quente.',
    'Cor de fubá peneirado na tigela de bolo.',
  ]),
  color('Ouro', 46, 85, 85, [
    'Amarelo dourado e forte, a cor do ouro de verdade e de medalha de campeão.',
    'Mais escuro e mais sério que o amarelo canário.',
    'Cor de moeda antiga que ninguém quer gastar.',
    'Dourado de moldura de quadro de museu, sem nenhum reflexo de espelho.',
    'Cor de anel de casamento, só que em tinta fosca.',
  ]),
  color('Creme', 48, 30, 100, [
    'Amarelo bem clarinho e suave, a cor do creme de leite com baunilha.',
    'Mais pálido que o amarelo banana, quase um branco quente.',
    'Cor de renda de toalha de mesa antiga.',
    'Amarelo de sorvete de creme depois de derreter um pouco.',
    'Cor de parede de sala de avó que sempre é aconchegante.',
  ]),
  color('Areia', 38, 35, 85, [
    'Bege dourado e meio apagado, a cor da areia seca da praia.',
    'Mais escuro e mais amarelado que o bege, parecido com biscoito de maisena.',
    'Cor de duna no deserto em foto de agência de viagem.',
    'Cor de calçada de praia depois de dias sem chuva.',
    'Cor de tapete de sisal que arranha o pé.',
  ]),
  color('Caramelo', 30, 75, 70, [
    'Marrom alaranjado e médio, a cor do caramelo derretido.',
    'Cor de calda de pudim escurecendo na panela.',
    'Mais claro que o chocolate e mais escuro que o mel.',
    'Cor de cachorro caramelo em pose de herói de rua.',
    'Cor de pele de bolacha de nata recém-assada.',
  ]),
  color('Terracota', 14, 60, 72, [
    'Laranja avermelhado e fosco, a cor do vaso de barro.',
    'Mais claro e mais rosado que o tijolo, mais apagado que o coral.',
    'Cor de telha de casa colonial iluminada pelo sol.',
    'Cor de vasinho de cacto de feira de artesanato.',
    'Cor de barro seco depois de assar no forno.',
  ]),
  color('Pimentão Vermelho', 3, 90, 80, [
    'Vermelho intenso e lustroso, a casca do pimentão vermelho.',
    'Mais escuro que o tomate, mas ainda bem vivo e sem nada de roxo.',
    'Cor de carro esportivo vermelho no estacionamento.',
    'Vermelho de placa de pare, forte e sem dúvida nenhuma.',
    'Cor de lata de refrigerante vermelha de marca famosa.',
  ]),
  color('Framboesa', 335, 75, 80, [
    'Rosa avermelhado e forte, a cor da framboesa madura.',
    'Mais rosado que a cereja e mais escuro que o morango.',
    'Cor da geleia de framboesa na torrada.',
    'Vermelho com um bom tanto de rosa e uma pitada de roxo.',
    'Cor de suco de frutas vermelhas bem concentrado.',
  ]),
  color('Goiaba', 355, 50, 95, [
    'Rosa avermelhado claro e suave, a polpa da goiaba vermelha.',
    'Entre o salmão e o rosa: mais rosado que o salmão e menos forte que o coral.',
    'Cor de goiabada cremosa batida com leite.',
    'Rosa quente e meio melancia, bem doce e fresco.',
    'Cor de bochecha corada de criança brincando no sol.',
  ]),
  color('Laranja Queimado', 16, 85, 90, [
    'Laranja avermelhado e forte, tipo o laranja do pôr do sol quando já está quase vermelho.',
    'Mais vermelho que a tangerina e mais claro que a ferrugem.',
    'Cor de cone de trânsito já meio desbotado de tanto sol.',
    'Cor de camiseta de seleção holandesa.',
    'Laranja de fogueira quando a lenha está no auge.',
  ]),
  color('Páprica', 8, 80, 72, [
    'Vermelho alaranjado e escuro, a cor da páprica em pó na colher.',
    'Mais fechado que o tomate e mais vermelho que a ferrugem.',
    'Cor de chouriço e de pimenta seca de tempero espanhol.',
    'Vermelho terroso e quente, com cara de cozinha de domingo.',
    'Cor de tempero espalhado em cima de batata assada.',
  ]),
  color('Rubi', 350, 92, 70, [
    'Vermelho profundo e intenso com um toque de rosa, a cor da pedra rubi.',
    'Mais rosado e mais joia que o vermelho sangue.',
    'Cor de coração de brilhante em anel de noiva.',
    'Vermelho de vinho tinto bem forte contra a luz da vela.',
    'Cor de batom de ópera, intenso e com muita atitude.',
  ]),
  color('Mamão', 24, 65, 98, [
    'Laranja suave e vivo, a polpa do mamão papaia aberto ao meio.',
    'Mais claro e mais macio que a cenoura, quase salmão alaranjado.',
    'Cor de suco de mamão com laranja no café da manhã.',
    'Alaranjado doce e leve, longe da ferrugem e da abóbora.',
    'Cor de gominha de mamão no pacote de frutas cristalizadas.',
  ]),
  color('Girassol', 50, 92, 98, [
    'Amarelo vivo e quente, a cor das pétalas do girassol aberto.',
    'Mais dourado que o amarelo canário, mais claro que o ouro.',
    'Cor de campo de flores amarelas em dia de céu azul.',
    'Amarelo de sol de meio-dia em foto de cartão-postal.',
    'Cor de ônibus escolar americano nos filmes.',
  ]),
  colorHex('Vermelho Puro', '#FF0000', [
    'O vermelho mais vermelho que existe, sem nenhum tom de laranja, rosa ou marrom.',
    'Cor de botão de emergência e de placa de proibido.',
    'Vermelho de caixa de correio inglesa e de telefone público de Londres.',
    'Vivo e forte demais para ser calmo, mais intenso que o tomate.',
    'Cor de lata de refrigerante famoso e de camisa de time que chama atenção.',
  ]),
  colorHex('Vermelho Bombeiro', '#CE2029', [
    'Vermelho forte e sério, um pouco mais escuro que o vermelho puro.',
    'Cor de caminhão de bombeiro correndo na avenida.',
    'Vermelho de extintor de incêndio na parede do corredor.',
    'Mais fechado que o tomate, sem laranja e sem rosa.',
    'Cor de sinaleira de ambulância antes de a sirene ligar.',
  ]),
  colorHex('Vermelho Maçã', '#D32F2F', [
    'Vermelho de maçã do amor, forte, firme e um pouco mais escuro que o tomate.',
    'Vermelho cheio de corpo, sem laranja, igual à casca de maçã gala.',
    'Cor de laço vermelho de presente de Natal.',
    'Entre o vermelho de bombeiro e o de tomate, mais suave que os dois.',
    'Cor de coraçãozinho de aplicativo quando você curte alguma coisa.',
  ]),
  colorHex('Vermelho Papoula', '#E35335', [
    'Vermelho alaranjado vivo, a cor da flor de papoula de campo.',
    'Mais claro e mais laranja que o tomate, com cara de verão.',
    'Cor de batom de dia ensolarado.',
    'Vermelho vibrante e leve, sem nada de sombra.',
    'Cor de pimenta malagueta madura no pé.',
  ]),
  colorHex('Escarlate', '#FF2400', [
    'Vermelho aceso com bastante laranja dentro, quase fogo.',
    'Cor de brasa de carvão quando você abana.',
    'Mais laranja que o vermelho puro e mais vivo que a papoula.',
    'Cor do traje do mágico no palco: vermelho que grita.',
    'Cor de lava de vulcão em desenho animado.',
  ]),
  colorHex('Romã', '#A4243B', [
    'Vermelho escuro e fechado com um toque de rosa, a casca da romã.',
    'Mais escuro que o carmim e mais vivo que o vinho.',
    'Cor de suco de romã misturado com um pouquinho de uva.',
    'Vermelho profundo e meio vinhoso, com ar de fruta rara.',
    'Cor de almofada de veludo vermelho escuro de sofá chique.',
  ]),
  colorHex('Bordô', '#800020', [
    'Vermelho bem escuro e arroxeado, o clássico bordô de vinho tinto.',
    'Mais escuro que o carmim, quase vinho, mas ainda nitidamente vermelho.',
    'Cor de capa de livro de luxo e de bolsa de couro cara.',
    'Vermelho de cadeira de cinema antigo.',
    'Cor de esmalte escuro de inverno que só aparece em maio.',
  ]),
  colorHex('Cardeal', '#C41E3A', [
    'Vermelho forte e frio, puxando um pouco para o rosa, a cor da batina de cardeal.',
    'Parecido com o carmim, só que um pouco mais vivo e mais escuro.',
    'Vermelho de pássaro cardeal pousado no galho de neve.',
    'Cor de lacre de carta antiga, derretido e profundo.',
    'Vermelho elegante de camisa de time tradicional.',
  ]),
  colorHex('Lagosta', '#B22222', [
    'Vermelho escuro e quente, a cor da lagosta cozida.',
    'Mais fechado que o vermelho de bombeiro, quase tijolo vivo.',
    'Cor de casca de camarão-gigante na travessa.',
    'Vermelho de sofá clássico de sala de jantar.',
    'Vermelho profundo, sem rosa e sem roxo, só vermelho escuro de verdade.',
  ]),
  colorHex('Vermelho Profundo', '#8B0000', [
    'Vermelho muito escuro e puro, quase na beirada do marrom.',
    'Cor de sangue seco e de tinta de carro antigo.',
    'Mais escuro que a lagosta, mas sem o roxo do bordô.',
    'Cor de cortina de teatro quando as luzes se apagam.',
    'Vermelho de maçã que passou muito tempo na geladeira.',
  ]),
  colorHex('Cinábrio', '#E34234', [
    'Vermelho alaranjado brilhante, a cor do pigmento de pintura chinesa.',
    'Mais claro que o vermelho de bombeiro e bem mais laranja.',
    'Cor de lacre de templo oriental e de laca de caixinha de chá.',
    'Vermelho quente e vivo, entre o tomate e a papoula.',
    'Cor de pimenta calabresa em pó espalhada na mesa.',
  ]),
  colorHex('Salmão Escuro', '#E9967A', [
    'Rosa alaranjado médio, mais fechado e mais escuro que o salmão clarinho.',
    'Cor de pele de salmão grelhado, com leve toque de terra.',
    'Entre o coral e o terracota, mais suave que os dois.',
    'Cor de camisa de linho de verão em cor de pele queimada.',
    'Rosa alaranjado fosco, com cara de tarde de praia no fim do dia.',
  ]),
  colorHex('Coral Claro', '#F08080', [
    'Rosa avermelhado claro e alegre, tipo uma melancia com um tantinho de laranja.',
    'Mais rosado que o coral e mais claro que o morango.',
    'Cor de bochecha com blush de maquiagem leve.',
    'Cor de gominha de morango cremosa.',
    'Rosa alegre com um fio de vermelho, doce de olhar.',
  ]),
  colorHex('Salmão Claro', '#FFA07A', [
    'Laranja rosado claro e luminoso, parecido com o salmão fresco.',
    'Mais laranja que o salmão escuro e mais vivo que o pêssego.',
    'Cor de gominho de pêssego em calda de lata.',
    'Cor de camisa polo de verão, daquelas de tom alaranjado suave.',
    'Cor de pôr do sol suave em foto de praia com filtro.',
  ]),
  colorHex('Laranja Fogo', '#FF4500', [
    'Laranja avermelhado bem aceso, quase vermelho com muita energia.',
    'Cor da chama de fogueira no meio da noite.',
    'Mais vermelho que a tangerina e mais laranja que o escarlate.',
    'Cor de colete de salva-vidas e de boia de resgate.',
    'Laranja de motor de foguete saindo da plataforma.',
  ]),
  colorHex('Laranja Vivo', '#FF8C00', [
    'Laranja forte e claro, entre o laranja de cenoura e o amarelo âmbar.',
    'Cor de abóbora de feira recém-colhida, bem laranja mesmo.',
    'Mais amarelado que a cenoura, mais escuro que o amarelo ouro.',
    'Cor de bola de tênis de cor chamativa e de capacete de obra.',
    'Cor de sinal luminoso de alerta em pista de aeroporto.',
  ]),
  colorHex('Laranja', '#FFA500', [
    'O laranja puro, a cor da laranja-pera: nem avermelhado, nem amarelado.',
    'Exatamente no meio do caminho entre o vermelho e o amarelo.',
    'Cor de fruta laranja inteira na fruteira.',
    'Mais claro que o laranja de cenoura e mais quente que o amarelo ouro.',
    'Cor do ícone de caixa de entrada de e-mail que ninguém abre.',
  ]),
  colorHex('Mexerica', '#F28C28', [
    'Laranja médio e doce, a casca da mexerica descascada.',
    'Mais suave que a tangerina, mais escuro e mais fosco.',
    'Cor de suco de laranja concentrado, tipo suco de caixinha.',
    'Cor de queijo cheddar derretido em cima de nachos.',
    'Laranja de camiseta de time do interior.',
  ]),
  colorHex('Pôr do Sol', '#FF8C61', [
    'Laranja rosado quente, a cor do céu pouco antes de o sol sumir.',
    'Mais rosado que a tangerina e mais laranja que o salmão.',
    'Cor de nuvem iluminada pelo sol baixo no fim da tarde.',
    'Cor de gominha de pêssego misturada com um toque de coral.',
    'Cor de lampadinha acesa dentro de um abajur laranja.',
  ]),
  colorHex('Melão', '#FDBE87', [
    'Laranja claro e suave com um toque de pêssego, a polpa do melão cantaloupe.',
    'Mais claro que o damasco e mais amarelado que o salmão.',
    'Cor de sorvete de melão com um pouquinho de leite.',
    'Cor de mel clarinho em pão de manhã.',
    'Laranja bem pastel, tipo parede de sorveteria.',
  ]),
  colorHex('Manga', '#FFB347', [
    'Laranja claro e dourado, a polpa da manga bem madura.',
    'Mais amarelado que a tangerina, mais claro que o âmbar.',
    'Cor de suco de manga num copo grande.',
    'Cor de pôr do sol tropical em praia do Nordeste.',
    'Laranja alegre e suculento que dá água na boca.',
  ]),
  colorHex('Maracujá', '#F2C04D', [
    'Amarelo dourado e suave, a polpa do maracujá com as sementinhas.',
    'Mais escuro que o amarelo banana e mais claro que o ouro.',
    'Cor de mousse de maracujá na sobremesa.',
    'Amarelo de suco de maracujá que você bebe antes de dormir.',
    'Amarelo quente com um toque alaranjado, como mel misturado com limão.',
  ]),
  colorHex('Abacaxi', '#F4D35E', [
    'Amarelo suave e quente, a polpa do abacaxi cortado em rodelas.',
    'Mais amarelo que o creme e mais claro que o ouro.',
    'Cor de suco de abacaxi com hortelã.',
    'Cor de pele de pera amarela bem madura.',
    'Cor de banana-prata madura cortada ao meio.',
  ]),
  colorHex('Limão Siciliano', '#FFF44F', [
    'Amarelo claríssimo e vivo, o limão siciliano cortado em fatias.',
    'Mais claro e mais ácido que o amarelo canário.',
    'Cor de marca-texto fluorescente amarelo-claro.',
    'Cor de limonada gelada na jarra de vidro.',
    'Amarelo de sinal luminoso de ciclovia e de colete de ciclista.',
  ]),
  colorHex('Amarelo Táxi', '#FDB813', [
    'Amarelo forte e dourado, cor de táxi de Nova York nos filmes.',
    'Cor de capa de chuva de pescador e de sinalização de obra.',
    'Mais alaranjado que o canário e mais vivo que o ouro.',
    'Amarelo de fita de interdição em local de acidente.',
    'Cor de motoboy de delivery correndo na faixa.',
  ]),
  colorHex('Açafrão', '#F4C430', [
    'Amarelo forte e quente com um fundo dourado, a cor do tempero açafrão.',
    'Cor de paella com arroz amarelinho de fim de semana.',
    'Mais alaranjado que o limão, mais claro que o ouro.',
    'Cor de gema de ovo cozida e esfarelada em cima de salada.',
    'Amarelo de lençol de seda de hotel de luxo.',
  ]),
  colorHex('Cúrcuma', '#E0A526', [
    'Amarelo alaranjado e terroso, a cor da cúrcuma em pó.',
    'Mais fechado que o açafrão e mais quente que a mostarda.',
    'Cor de curry em pó espalhado na bancada da cozinha.',
    'Dourado fosco, como mel que cristalizou no pote.',
    'Cor de pele de pão de milho bem assado.',
  ]),
  colorHex('Curry', '#B8860B', [
    'Amarelo escuro e meio marrom, a cor do curry bem cozido na panela.',
    'Mais fechado que a mostarda, quase terra, mas ainda amarelado.',
    'Cor de sofá de couro antigo de escritório.',
    'Cor de ouro velho que já não reluz.',
    'Dourado escuro de caixinha de joia herdada.',
  ]),
  colorHex('Dourado', '#FFD700', [
    'Amarelo dourado puro e vivo, a cor da medalha de ouro do pódio.',
    'Mais escuro e mais quente que o canário, mas ainda muito claro.',
    'Cor de coroa de rei de desenho animado.',
    'Cor de purpurina de enfeite de Natal, em tom de ouro.',
    'Amarelo de barra de ouro empilhada em filme de assalto.',
  ]),
  colorHex('Ouro Velho', '#CFB53B', [
    'Dourado esverdeado e antigo, como ouro de moeda velha.',
    'Mais apagado que o dourado, quase cor de latão polido.',
    'Cor de moldura de quadro antigo que já está meio desbotada.',
    'Mais amarelo-esverdeado que o âmbar e mais claro que a mostarda.',
    'Cor de maçaneta de latão de casa velha.',
  ]),
  colorHex('Amarelo Sol', '#FFC300', [
    'Amarelo forte e alaranjado, a cor do sol brilhando em dia de verão.',
    'Mais escuro e mais laranja que o amarelo canário.',
    'Cor de caixa de ferramentas amarela de oficina.',
    'Cor de gema de ovo de galinha caipira em pote.',
    'Amarelo de ônibus escolar que ninguém perde de vista.',
  ]),
  colorHex('Manteiga', '#FFE97F', [
    'Amarelo clarinho e cremoso, a cor da manteiga mole em temperatura ambiente.',
    'Mais suave que o banana e mais quente que o creme.',
    'Cor de pãozinho de leite assado, por dentro.',
    'Amarelo de gema de ovo cozida e machucada com garfo.',
    'Cor de cobertura de bolo de baunilha feito em casa.',
  ]),
  colorHex('Amarelo Bandeira', '#FFDF00', [
    'O amarelo da bandeira do Brasil, forte e dourado, sem nada de verde.',
    'Cor do losango da bandeira nacional no estádio.',
    'Mais forte que o creme, mais puro que o ouro.',
    'Amarelo da camisa da seleção brasileira nos dias de jogo.',
    'Cor de fita de pulseira do Senhor do Bonfim em amarelo vivo.',
  ]),
  colorHex('Amarelo Queimado', '#E6B422', [
    'Amarelo dourado e quente, como mel que passou do ponto.',
    'Mais fechado que o ouro, quase mostarda clara.',
    'Cor de torrada bem dourada, antes de queimar.',
    'Amarelo de cevada madura no campo, antes da colheita.',
    'Cor de grão de milho seco guardado no armário.',
  ]),
];
