import { color, colorHex, type PaletteColor } from './palette-types';

/** Verdes, do limão ao verde-garrafa. */
export const PALETTE_2: PaletteColor[] = [
  color('Verde Folha', 120, 70, 65, [
    'Verde médio e puro, a cor da folha de árvore em dia comum, sem amarelo nem azul.',
    'Cor de couve crua inteira: verde firme e natural.',
    'Metade do caminho entre o verde limão e o verde de floresta.',
    'Cor de gramado de praça bem cuidada, daquele em que ninguém pode pisar.',
    'Verde de horta de avó, cheio de cheiro-verde e couve.',
  ]),
  color('Verde Limão', 80, 85, 95, [
    'Verde bem claro e vivo com muito amarelo dentro, quase fluorescente.',
    'Cor de bala azeda que faz careta antes mesmo de mastigar.',
    'Verde de marca-texto, mais amarelado que a folha e mais ácido que a maçã verde.',
    'Cor de raspa de limão ralada em cima da caipirinha.',
    'Se o verde tomasse café forte e ficasse agitado, seria assim.',
  ]),
  color('Verde Neon', 110, 80, 100, [
    'Verde fortíssimo e luminoso, tipo luz de letreiro de loja de conveniência.',
    'Cor de pulseira de show que ainda acende às três da manhã.',
    'Tão forte que dói olhar: nada de pastel, nada de sombra.',
    'Cor do slime que a sobrinha jura que é de brinquedo.',
    'Verde de líquido radioativo de desenho animado, daqueles que escorrem do barril.',
  ]),
  color('Verde Maçã', 95, 70, 85, [
    'Verde claro e amarelado, a casca da maçã verde bem lavada.',
    'Cor de bala de maçã verde que sempre sobra no pote.',
    'Meio caminho entre o verde limão e a folha: fresco e azedinho.',
    'Cor de gelatina de maçã verde balançando no prato.',
    'Verde de embalagem de chiclete que promete sabor natural e não cumpre.',
  ]),
  color('Verde Pistache', 85, 35, 90, [
    'Verde bem clarinho e meio acinzentado, cor de sorvete de pistache.',
    'Verde pastel com um fundo amarelado, bem suave e discreto.',
    'Cor de macaron francês que custa o triplo do que deveria.',
    'Cor de parede de consultório de dentista: calma e um pouco antiga.',
    'Cor de geladeira retrô dos anos cinquenta.',
  ]),
  color('Verde Menta', 150, 30, 95, [
    'Verde bem clarinho e fresco com um toque azulado, cor de bala de menta.',
    'Pasta de dente em gel bem aberta: pastel e gelada.',
    'Mais azulado que o pistache e mais claro que o verde jade.',
    'Cor de sabonete de hotel que você leva na mala sem culpa.',
    'Cor do picolé de menta com pedacinhos de chocolate.',
  ]),
  color('Verde Floresta', 140, 80, 35, [
    'Verde bem escuro, de floresta fechada onde o sol mal entra.',
    'Cor de mesa de bilhar, só que mais fundo e mais sério.',
    'Cor dos pinheiros vistos de longe à noite.',
    'Verde de livro antigo de capa dura na estante do escritório.',
    'Escuro e frio: nada de amarelo, só mato fechado.',
  ]),
  color('Verde Musgo', 80, 60, 45, [
    'Verde escuro, amarelado e apagado, cor de musgo em pedra úmida.',
    'Cor de roupa militar discreta de acampamento.',
    'Verde terroso, quase marrom, sem nada de reluzente.',
    'Cor de pântano em dia nublado.',
    'Cor de barraca de camping herdada de um parente distante.',
  ]),
  color('Verde Oliva', 65, 70, 50, [
    'Verde escuro e amarelado, a cor da azeitona verde.',
    'Verde de uniforme do exército, entre o musgo e o marrom.',
    'Cor de lata de conserva esquecida no fundo do armário.',
    'Cor do azeite quando a luz bate de lado na garrafa.',
    'Parece sujo, mas de um jeito chique.',
  ]),
  color('Verde Esmeralda', 150, 85, 75, [
    'Verde vivo e profundo com um toque de azul, cor de joia esmeralda.',
    'Cor de pedra de anel de rainha em retrato antigo.',
    'Mais frio que a folha e mais claro que o verde floresta.',
    'O verde do trevo de quatro folhas de quem tem muita sorte.',
    'Cor de vestido de gala que ninguém usa duas vezes.',
  ]),
  color('Verde Bandeira', 144, 100, 61, [
    'O verde da bandeira do Brasil: forte, escuro e cheio de orgulho.',
    'Cor da camisa da seleção no gramado, vista de longe.',
    'Verde de campo de futebol visto na televisão antiga.',
    'Mais escuro que a esmeralda e sem aquele ar de joia.',
    'Verde de pano de bandeira pendurado na janela do vizinho em dia de Copa.',
  ]),
  color('Verde Abacate', 78, 55, 70, [
    'Verde amarelado e macio, a polpa do abacate no ponto.',
    'Cor de guacamole que alguém deixou sem limão e escureceu um pouquinho.',
    'Verde claro com amarelo, mais apagado que o verde limão.',
    'Cor de sofá retrô dos anos setenta que voltou à moda.',
    'Cor da torrada de abacate das fotos de café da manhã chique.',
  ]),
  color('Verde Jade', 160, 60, 65, [
    'Verde-azulado médio e calmo, cor de pedra de jade polida.',
    'Cor de colar que a tia tirou da caixinha para o casamento.',
    'Verde frio e profundo, mais azul que a folha e menos vivo que a esmeralda.',
    'Cor do chá verde quando ainda não ficou forte demais.',
    'Cor de louça chinesa que ninguém pode quebrar.',
  ]),
  color('Verde Água', 165, 45, 85, [
    'Verde-azulado claro e suave, cor de água de piscina limpa com um fundo esverdeado.',
    'Cor da água do mar caribenho em foto de agência de viagem.',
    'Entre a menta e o turquesa, bem calmo e fresco.',
    'Cor de aquário limpo com plantinhas.',
    'Cor de parede de banheiro que quer parecer spa.',
  ]),
  colorHex('Chartreuse', '#7FFF00', [
    'Verde amarelado ultravivo, entre o verde limão e o verde-grama de cartaz.',
    'Cor de licor francês de monge, daqueles que brilham na garrafa.',
    'Verde mais amarelo que a folha e mais forte que a maçã verde.',
    'Cor de gel de cabelo dos anos noventa.',
    'Verde de caneta marca-texto verde, aquela que sempre acaba antes.',
  ]),
  colorHex('Verde-Amarelado', '#ADFF2F', [
    'Verde bem claro, com tanto amarelo que parece fluorescente.',
    'Cor de marca-texto do cantinho mais ácido da caixa de canetas.',
    'Mais amarelo que o limão e mais claro que o chartreuse.',
    'Cor de bala de limão com pozinho azedo por fora.',
    'Verde de brinquedo de plástico que brilha sob a luz negra.',
  ]),
  colorHex('Verde Kelly', '#4CBB17', [
    'Verde vivo e alegre de gramado de campo de golfe bem regado.',
    'Cor de trevo de camiseta de dia de São Patrício.',
    'Verde forte e limpo, entre o limão e a folha.',
    'Cor de capa de livro infantil sobre natureza.',
    'Verde de semáforo liberado em desenho de criança.',
  ]),
  colorHex('Verde Pimentão', '#4C9A2A', [
    'Verde médio e vivo, a casca do pimentão verde lustroso.',
    'Cor de folha de couve-flor e de talo de salsão.',
    'Mais escuro que o verde limão e mais claro que o verde floresta.',
    'Verde de horta bem cuidada em manhã de sol.',
    'Cor de mochila escolar verde de menino que gosta de dinossauro.',
  ]),
  colorHex('Ervilha', '#9ACD32', [
    'Verde claro e amarelado, a cor da ervilha fresca na vagem.',
    'Mais suave que o chartreuse, com cara de legume de panela de pressão.',
    'Cor de purê de ervilha servido em prato de bebê.',
    'Verde de folhinha nova de planta de apartamento.',
    'Verde de bala de goma de maçã verde.',
  ]),
  colorHex('Alface', '#7CB342', [
    'Verde médio e fresco, a folha da alface-crespa na salada.',
    'Cor da primavera em foto de feira orgânica.',
    'Mais escuro que a ervilha e mais amarelo que o brócolis.',
    'Verde de folha de horta recém-regada em dia de sol.',
    'Verde de adesivo de produto sustentável de rótulo.',
  ]),
  colorHex('Brócolis', '#3F7D3A', [
    'Verde escuro e firme, a cor do florete de brócolis cozido.',
    'Verde de folhas grossas de couve-de-bruxelas.',
    'Mais fechado que a alface e mais vivo que o verde musgo.',
    'Cor de roupa de médico de série, entre o verde e o escuro.',
    'Verde de horta mais séria, do tipo que ninguém quer comer.',
  ]),
  colorHex('Verde Pinheiro', '#01796F', [
    'Verde-azulado escuro e fundo, a cor das agulhas do pinheiro à sombra.',
    'Mais azulado que o verde floresta e mais verde que o azul petróleo.',
    'Verde de lagoa fechada em dia nublado.',
    'Cor de mesa de bilhar chique de clube de campo.',
    'Verde de capa de caderno de escola tradicional.',
  ]),
  colorHex('Verde Caçador', '#355E3B', [
    'Verde escuro e apagado, o verde de roupa de caçador na mata.',
    'Mais acinzentado que o verde floresta e mais claro que o abeto.',
    'Cor de capa de chuva de pescador em dia frio.',
    'Verde de poltrona de clube inglês onde ninguém fala alto.',
    'Verde de folhagem de árvore antiga debaixo de chuva fina.',
  ]),
  colorHex('Verde Mata', '#228B22', [
    'Verde médio e cheio, a cor das árvores na mata fechada de dia.',
    'Verde de gramado de estádio com iluminação de domingo.',
    'Mais vivo que o brócolis e mais escuro que o verde kelly.',
    'Cor de uniforme de time de futebol americano do colégio.',
    'Verde de selva em desenho animado, bem folhudo.',
  ]),
  colorHex('Verde Escuro', '#006400', [
    'Verde muito escuro e puro, o verde mais fechado antes de virar quase preto.',
    'Cor de folha de louro grossa e velha.',
    'Mais escuro que a mata e sem aquele tom azulado do pinheiro.',
    'Verde de bolsa de couro verde escuro de gente séria.',
    'Verde de fundo de mesa de feltro de cassino.',
  ]),
  colorHex('Kiwi', '#8EE53F', [
    'Verde claro e vivo com um toque de amarelo, a polpa do kiwi fatiado.',
    'Cor de limão verde cortado ao meio.',
    'Mais claro que a alface e mais vivo que a ervilha.',
    'Verde de gelatina de kiwi com pedacinhos dentro.',
    'Verde de refresco de limonada com hortelã.',
  ]),
  colorHex('Pepino', '#7FB069', [
    'Verde suave e fresco, cor da casca do pepino cortado.',
    'Mais apagado que a alface, com um ar de salada de verão.',
    'Cor de máscara facial de spa, com rodelas de pepino nos olhos.',
    'Verde suave e acinzentado, bem calmo.',
    'Cor de folha de hortelã em cima do copo de gim.',
  ]),
  colorHex('Aspargo', '#87A96B', [
    'Verde suave e acinzentado, a cor do aspargo cozido no vapor.',
    'Verde apagado de folha de oliveira ao sol.',
    'Mais cinza que o pepino, com jeito de verde de caixinha de chá.',
    'Cor de móvel de cozinha em tom suave, tipo sálvia.',
    'Verde de couve-flor embalada em plástico.',
  ]),
  colorHex('Verde Sapo', '#5B8C2A', [
    'Verde médio e amarelado, a pele do sapo-cururu.',
    'Cor de folha de nenúfar boiando na lagoa.',
    'Mais escuro que a alface e mais vivo que o musgo.',
    'Verde de plástico de brinquedo de sapinho.',
    'Cor de tapete de grama sintética de varanda.',
  ]),
  colorHex('Verde Primavera', '#00FF7F', [
    'Verde bem vivo e claro com um toque azulado, como um gramado de neon.',
    'Cor de gel de limpeza fluorescente.',
    'Mais azulado que o limão e mais vivo que a menta.',
    'Verde de luz de LED verde-água ligada sozinha.',
    'Cor de lista de status "tudo certo" em painel de computador.',
  ]),
  colorHex('Verde Hortelã', '#98FB98', [
    'Verde bem clarinho e fresco, cor de folha nova de hortelã.',
    'Cor de bala de menta verde escorrendo da embalagem.',
    'Mais vivo que o pistache e mais verde que a menta clara.',
    'Cor de chiclete de menta que dura dez segundos.',
    'Verde claro de bolinha de pastilha de hortelã.',
  ]),
  colorHex('Verde Clarinho', '#90EE90', [
    'Verde claro e suave, bem alegre, tipo gramado de desenho infantil.',
    'Cor de lápis de cor verde-claro que sempre sobra no estojo.',
    'Mais vivo que o pepino e mais claro que o verde maçã.',
    'Verde de salada de folhas novas em prato branco.',
    'Verde de balão de festa de aniversário infantil.',
  ]),
  colorHex('Verde Mar', '#2E8B57', [
    'Verde médio com um toque azulado, a cor da água do mar de manhã.',
    'Verde de alga em pedra de costão rochoso.',
    'Mais azulado que o brócolis e mais verde que o jade.',
    'Cor de mata atlântica vista de cima.',
    'Verde de garrafa de vidro de água mineral importada.',
  ]),
  colorHex('Eucalipto', '#5E8C6A', [
    'Verde médio e acinzentado, a folha do eucalipto de perto.',
    'Cor de sabonete de ervas num banheiro de spa.',
    'Mais cinza que o verde mar, com jeito de planta de jardim.',
    'Verde de poltrona de sala de espera de clínica de beleza.',
    'Cor de parede de casa de campo em tom de verde sossegado.',
  ]),
  colorHex('Verde Abeto', '#123524', [
    'Verde quase preto, o verde mais fundo de uma floresta de abetos à noite.',
    'Cor da folha do pinheiro de Natal sem as luzinhas.',
    'Mais escuro que o verde escuro, com um fundo azulado.',
    'Verde de capa de livro de fantasia sombria.',
    'Cor de fundo de apresentação que quer parecer elegante e natural.',
  ]),
  colorHex('Verde Cacto', '#4E8F6B', [
    'Verde médio e frio, a cor do cacto de vaso na janela.',
    'Verde de folha de babosa cortada ao meio.',
    'Mais azulado que o pepino, mais claro que o verde mar.',
    'Cor de sofá de veludo verde de apartamento moderno.',
    'Verde de embalagem de produto vegano em prateleira de mercado.',
  ]),
  colorHex('Água-Marinha', '#7FFFD4', [
    'Verde-azulado claro e luminoso, cor da pedra água-marinha.',
    'Cor do mar de piscina natural com areia branca embaixo.',
    'Mais claro que o turquesa e mais verde que o azul piscina.',
    'Cor de picolé de menta e coco numa tarde quente.',
    'Cor de bala de goma azul-esverdeada de saquinho de festa.',
  ]),
  colorHex('Verde Névoa', '#CFE8D5', [
    'Verde bem pálido e acinzentado, quase branco, como uma névoa de manhã.',
    'Cor de parede de sala de espera de consultório.',
    'Mais claro que a menta e bem mais suave.',
    'Cor de sabonete de pepino num hotel simples.',
    'Verde de embalagem de chá de camomila com hortelã.',
  ]),
  colorHex('Verde Alga', '#3B7A57', [
    'Verde escuro e frio com um fundo azulado, a cor da alga marinha cozida.',
    'Cor de rolinho de sushi enrolado com folha de nori.',
    'Mais escuro que o verde mar e mais claro que o pinheiro.',
    'Cor de capa de livro sobre o fundo do mar.',
    "Verde de roupa de mergulhador dentro d'água turva.",
  ]),
  colorHex('Verde Cana', '#A9C23F', [
    'Verde amarelado médio, a cor do caule da cana-de-açúcar.',
    'Cor de plantação de cana no campo ao sol.',
    'Mais escuro que o verde limão e mais claro que o musgo.',
    'Verde de caldo de cana espremido, bem verdinho.',
    'Cor de folha de capim-limão no quintal.',
  ]),
  colorHex('Chá Verde', '#B6C28F', [
    'Verde suave e acinzentado, a cor do chá verde servido na xícara.',
    'Mais apagado que o pistache, com um toque de terra.',
    'Cor de talo de cebolinha cortado.',
    'Verde de embalagem de sabonete de ervas.',
    'Cor de folha seca de erva-mate esfarelada.',
  ]),
  colorHex('Verde Vidro', '#A3C9A8', [
    'Verde claro e suave, a cor do vidro de garrafa de refrigerante contra a luz.',
    'Cor de pedra de rio polida pela água.',
    'Mais calmo que o verde hortelã e mais claro que o eucalipto.',
    'Cor de bolinha de gude verde-clara de coleção.',
    'Verde de garrafa de água gaseificada de marca chique.',
  ]),
  colorHex('Verde Lagoa', '#2A9D8F', [
    'Verde-azulado médio e vivo, cor de água de lagoa em dia de sol.',
    'Cor de azulejo de piscina antiga.',
    'Mais azulado que o jade e mais verde que o turquesa.',
    'Cor de camiseta de time de futebol que ninguém lembra o nome.',
    'Verde de capa de caderno de faculdade de biologia.',
  ]),
  colorHex('Verde Selva', '#1F7A4D', [
    'Verde médio e escuro com um fundo frio, a cor da folhagem na floresta tropical.',
    'Mais fechado que o verde mar e mais claro que o abeto.',
    'Cor de pano de sinuca de bar tradicional.',
    'Verde de papel de parede de sala de visitas chique.',
    'Verde de folha de bananeira no quintal.',
  ]),
];
