import { color, colorHex, type PaletteColor } from './palette-types';

/** Neutros: brancos, cinzas, pretos, bege e pastéis. */
export const PALETTE_4: PaletteColor[] = [
  color('Branco Gelo', 210, 4, 98, [
    'Branco puro com um sopro de frio, quase azulado, cor de geladeira nova.',
    'Quase sem cor nenhuma, mas ainda sem chegar ao cinza.',
    'Branco de papel de impressora novo, daquele que ofusca.',
    'Cor de parede de clínica estética que cobra caro.',
    'Branco que fica estranho ao lado de qualquer outro branco.',
  ]),
  color('Off-White', 45, 8, 97, [
    'Branco com um fio amarelado, de papel de caderno antigo.',
    'Cor de parede de casa de campo que ninguém repinta há anos.',
    'Mais amarelado que o branco gelo e bem menos creme que o marfim.',
    'Cor de lençol de algodão lavado cem vezes.',
    'Branco de vestido de noiva que não quer parecer branco demais.',
  ]),
  color('Marfim', 55, 12, 100, [
    'Branco levemente amarelado, a cor das teclas de piano e do dente de elefante.',
    'Cor de convite de casamento que custou uma fortuna.',
    'Mais amarelinho que o off-white e menos amarelo que o creme.',
    'Cor de renda de vestido da bisavó.',
    'Branco com cara de coisa herdada.',
  ]),
  color('Cinza Claro', 0, 0, 85, [
    'Cinza bem claro, quase prata, sem nenhum tom de cor.',
    'Cor de parede de escritório de empresa de médio porte.',
    'Mais claro que o cinza médio e menos frio que a prata.',
    'Cor de calçada limpa em manhã nublada.',
    'Cor de moletom que combina com tudo e ninguém nota.',
  ]),
  color('Cinza Concreto', 40, 6, 62, [
    'Cinza médio e levemente amarelado, a cor do concreto sem pintura.',
    'Cor de parede de obra que nunca recebeu tinta.',
    'Mais quente que o cinza chumbo e mais escuro que o cinza claro.',
    'Cor de calçada rachada de bairro antigo.',
    'Cor de saco de cimento aberto e deixado na chuva.',
  ]),
  color('Cinza Médio', 0, 0, 55, [
    'Cinza exatamente no meio do caminho entre o branco e o preto.',
    'Cor de fundo de foto de documento.',
    'Cor de asfalto novo antes de ficar preto.',
    'Mais escuro que o concreto e mais claro que o chumbo.',
    'Cor do botão desabilitado de site.',
  ]),
  color('Cinza Azulado', 210, 18, 60, [
    'Cinza médio com um toque de azul, cor de nuvem de chuva próxima.',
    'Cor de terno cinza de reunião de banco.',
    'Mais frio que o cinza médio e mais claro que o chumbo.',
    'Cor de ardósia, daquela pedra que vira lousa.',
    'Cor de céu de cidade grande em dia de garoa.',
  ]),
  color('Prata', 210, 6, 78, [
    'Cinza claro e frio, com cara de metal polido.',
    'Cor de talher bom que só sai em ocasião especial.',
    'Mais claro que o cinza azulado e mais frio que o cinza claro.',
    'Cor de lata de refrigerante fosca.',
    'Cor de medalha de segundo lugar.',
  ]),
  color('Cinza Chumbo', 210, 10, 35, [
    'Cinza escuro e pesado, com um sopro de azul, cor de metal que afunda na água.',
    'Cor de céu de tempestade antes da primeira trovoada.',
    'Mais escuro que o cinza azulado e mais claro que o grafite.',
    'Cor de asfalto molhado à noite.',
    'Cor de terno de pessoa que fala baixo e manda em tudo.',
  ]),
  color('Grafite', 220, 12, 25, [
    'Cinza quase preto, cor de lápis de desenhista.',
    'Cor de lousa de sala de aula depois de apagada.',
    'Mais escuro que o chumbo e mais claro que o preto carvão.',
    'Cor de carcaça de aparelho eletrônico caro.',
    'Cinza que parece preto até alguém acender uma luz.',
  ]),
  color('Preto Carvão', 0, 0, 12, [
    'Preto quase absoluto, só um pouquinho acima do escuro total.',
    'A cor do carvão do churrasco antes de acender.',
    'Cor de tela de TV desligada em sala escura.',
    'Preto de roupa de festa em que ninguém quer errar.',
    'Cor de gato preto passando atrás da cortina.',
  ]),
  color('Ébano', 30, 30, 18, [
    'Preto com um fundo marrom, a cor da madeira escura e densa.',
    'Cor de piano de cauda de sala de concerto.',
    'Mais quente que o carvão e mais escuro que o chocolate.',
    'Cor de caixa de charuto vazia.',
    'Cor de café passado sem açúcar e sem remorso.',
  ]),
  color('Marrom Chocolate', 20, 70, 30, [
    'Marrom escuro e intenso, a cor do chocolate meio amargo.',
    'Cor de barra de chocolate com muito cacau.',
    'Mais avermelhado que o ébano e mais escuro que o café.',
    'Cor de brownie ainda quente no meio.',
    'Marrom de sofá de couro de escritório de advogado.',
  ]),
  color('Marrom Café', 25, 60, 40, [
    'Marrom escuro e quente, a cor do café coado na hora.',
    'Cor de grão de café torrado esperando a máquina.',
    'Mais claro que o chocolate e mais escuro que a madeira.',
    'Cor de borra de café na xícara depois da fofoca.',
    'Cor de bota de trabalho que já andou muito.',
  ]),
  color('Marrom Madeira', 25, 65, 55, [
    'Marrom médio e quente, a cor de madeira de lei de móvel pesado.',
    'Cor de mesa de jantar de família grande.',
    'Mais claro que o café e mais quente que a castanha.',
    'Marrom de violão antigo bem cuidado.',
    'Cor de banco de praça que ninguém tem coragem de pichar.',
  ]),
  color('Castanha', 15, 55, 35, [
    'Marrom escuro e avermelhado, a cor da castanha assada no Natal.',
    'Cor de cabelo castanho escuro de quem acabou de pintar.',
    'Mais avermelhada que o café e menos preta que o ébano.',
    'Cor de móvel de mogno bem lustrado.',
    'Marrom de casca de árvore em dia úmido.',
  ]),
  color('Bege', 40, 20, 92, [
    'Marrom muito clarinho misturado com branco, cor de areia seca e de capa de trench coat.',
    'Cor de sofá que todo mundo escolhe para não errar.',
    'Mais claro e mais rosado que o cáqui, mais escuro que o creme.',
    'Cor de biscoito de maisena saindo do pacote.',
    'Cor de parede de consultório que quer acalmar.',
  ]),
  color('Cáqui', 45, 30, 76, [
    'Bege escurecido com um fundo meio esverdeado, cor de calça de explorador.',
    'Cor de chapéu de aventureiro que nunca viajou.',
    'Mais escuro e mais amarelado que o bege.',
    'Cor de mochila de excursão escolar.',
    'Cor de bermuda de homem que sempre diz que ama praia.',
  ]),
  color('Nude', 25, 22, 90, [
    'Bege rosado muito claro, cor de esmalte discreto e de sapatilha de balé.',
    'Quase da cor de uma pele clara, só um pouquinho mais rosada.',
    'Mais rosado que o bege e mais claro que o café com leite.',
    'Cor de batom que diz "não estou de batom".',
    'Cor de parede de salão de maquiagem.',
  ]),
  color('Café com Leite', 28, 35, 75, [
    'Marrom suave e cremoso, o tom exato do café com muito leite.',
    'Cor de capuccino com espuma, antes de mexer.',
    'Mais escuro que o bege e mais claro que a madeira.',
    'Cor de calda de doce de leite que acabou de esfriar.',
    'Cor de cachorro caramelo dormindo no sol.',
  ]),
  color('Sálvia', 100, 22, 70, [
    'Verde suave e acinzentado, a cor da folha de sálvia seca.',
    'Cor de parede de casa de campo moderna.',
    'Mais cinza que o verde menta e mais verde que o cinza azulado.',
    'Cor de móvel de cozinha escandinava.',
    'Cor de almofada de decoração de loja minimalista.',
  ]),
  color('Verde Garrafa', 150, 85, 28, [
    'Verde bem escuro e fechado, a cor do vidro de garrafa de vinho.',
    'Quase preto, mas ainda verde.',
    'Cor de poltrona de clube inglês onde ninguém fala alto.',
    'Mais escuro que o verde floresta e mais azulado que o musgo.',
    'Cor de vidro de remédio antigo na estante da avó.',
  ]),
  color('Verde Pastel', 125, 25, 95, [
    'Verde bem clarinho e suave, de pastel de confeitaria.',
    'Cor de glacê de bolo de chá de bebê.',
    'Mais amarelado que a menta e mais claro que o pistache.',
    'Verde de cortina de berçário.',
    'Cor de plástico de brinquedo de criança pequena.',
  ]),
  color('Amarelo Pastel', 55, 25, 100, [
    'Amarelo clarinho e macio, cor de manteiga fresca.',
    'Cor de glacê de cupcake em chá de bebê.',
    'Mais pálido que o creme e mais vivo que o branco.',
    'Cor de pintinho recém-nascido.',
    'Cor de lençol de berço com bolinhas.',
  ]),
  color('Azul Pastel', 215, 25, 100, [
    'Azul bem clarinho e delicado, de céu de desenho de bebê.',
    'Cor de glacê de bolo de menino em chá de bebê.',
    'Mais forte que o azul gelo e mais claro que o céu.',
    'Cor de roupinha de enxoval de neném.',
    'Cor de camiseta polo que combina com tudo no escritório.',
  ]),
  color('Laranja Pastel', 28, 28, 100, [
    'Laranja clarinho e suave, quase um pêssego pálido.',
    'Cor de sorvete de creme de laranja derretendo.',
    'Mais pálido que o damasco e mais quente que o creme.',
    'Cor de babado de roupa infantil de verão.',
    'Cor de gominha de tangerina de saquinho de festa.',
  ]),
  color('Menta Pastel', 160, 15, 100, [
    'Verde-azulado clarinho, quase branco, de bala de menta suave.',
    'Cor de sorvete de hortelã com chocolate branco.',
    'Mais pálido e mais azulado que o verde pastel.',
    'Cor de lençol de hotel de luxo que ninguém ousa sujar.',
    'Cor de espuma de sabão de menta.',
  ]),
  color('Greige', 35, 12, 72, [
    'Cinza com um fundo de bege, meio cinza meio bege, daí o nome.',
    'Cor de parede de apartamento recém-reformado por arquiteto.',
    'Mais quente que o cinza claro e menos amarelo que o bege.',
    'Cor de sofá de linho que combina com decoração escandinava.',
    'Cor de pelo de gato cinza de tom quente.',
  ]),
  colorHex('Linho', '#FAF0E6', [
    'Branco levemente rosado e quente, a cor do tecido de linho cru.',
    'Mais rosado que o off-white e menos amarelo que o marfim.',
    'Cor de toalha de mesa de linho passada de manhã.',
    'Cor de camisa de verão em tom de areia clara.',
    'Branco suave de cortina de sala em tarde de sol.',
  ]),
  colorHex('Casca de Ovo', '#F0EAD6', [
    'Branco amarelado e fosco, a cor da casca de ovo branco de granja.',
    'Mais quente e mais escuro que o marfim, com um fundo de creme.',
    'Cor de parede de casa antiga pintada com tinta fosca.',
    'Cor de porcelana de xícara de vó.',
    'Cor de papel de carta envelhecido.',
  ]),
  colorHex('Seda', '#FFF8DC', [
    'Amarelo-creme bem clarinho, quase branco, a cor da seda do milho.',
    'Mais amarelinho que o marfim e mais pálido que o creme.',
    'Cor de espiga de milho verde com a palha aberta.',
    'Cor de manteiga clara em pote de vidro.',
    'Cor de renda bordada de vestido de batizado.',
  ]),
  colorHex('Osso', '#E3DAC9', [
    'Bege muito clarinho e acinzentado, a cor de osso seco e limpo.',
    'Mais escuro que o linho e mais cinza que o off-white.',
    'Cor de botão antigo de camisa feito de madrepérola.',
    'Cor de capa de livro de capa branca já amarelada.',
    'Cor de parede de museu de história natural.',
  ]),
  colorHex('Cinza Pedra', '#8E8E8A', [
    'Cinza médio e levemente esverdeado, cor de seixo de rio.',
    'Cor de muro de pedra seca em sítio do interior.',
    'Mais claro que o chumbo e mais quente que o cinza azulado.',
    'Cor de calçada de paralelepípedo em dia seco.',
    'Cor de pedra de jardim zen entre as árvores.',
  ]),
  colorHex('Ardósia', '#708090', [
    'Cinza azulado médio, a cor da lousa de ardósia.',
    'Mais claro que o chumbo e mais azul que a pedra.',
    'Cor de telhado de casa de montanha no inverno.',
    'Cor de nuvem de tempestade se aproximando devagar.',
    'Cor de capa de agenda executiva que combina com tudo.',
  ]),
  colorHex('Cinza Fosco', '#A9A9A9', [
    'Cinza médio e puro, sem tom de cor, a cor da fumaça de vela apagada.',
    'Mais claro que o cinza médio e mais escuro que o cinza claro.',
    'Cor de calçada de cimento em dia nublado.',
    'Cor de peça de computador que ninguém lembra de ter comprado.',
    'Cinza de caixa de som portátil barata.',
  ]),
  colorHex('Cinza Neblina', '#DCDCDC', [
    'Cinza claríssimo e neutro, cor de neblina densa.',
    'Mais claro que o cinza claro, com um jeito de papel de embalagem.',
    'Cor de parede de escritório recém-pintado.',
    'Cor de nuvem alta e fina em dia de sol fraco.',
    'Cinza de roupa de academia lavada muitas vezes.',
  ]),
  colorHex('Cinza Fumaça', '#696969', [
    'Cinza escuro e puro, cor de fumaça de chaminé de fábrica.',
    'Mais escuro que o cinza médio e mais claro que o grafite.',
    'Cor de calçada molhada em dia de chuva fina.',
    'Cor de moletom de academia, bem escuro.',
    'Cinza de tela de computador em modo economia.',
  ]),
  colorHex('Cinza Pombo', '#8A8D93', [
    'Cinza médio com um fundo de azul, a cor das penas do pombo de praça.',
    'Mais frio que o cinza fosco e mais claro que o cinza ardósia.',
    'Cor de calça de moletom de inverno.',
    'Cor de asfalto velho, desbotado de tanto sol.',
    'Cinza de nuvem carregada que ainda não chove.',
  ]),
  colorHex('Cinza Gelo', '#E5E7EB', [
    'Cinza bem claro e frio, quase branco, com um sopro de azul.',
    'Mais claro que o cinza neblina e mais frio.',
    'Cor de parede de clínica com luz fria.',
    'Cor de gelo seco depois que a fumaça passa.',
    'Cinza de fundo de aplicativo com tema claro.',
  ]),
  colorHex('Cinza Asfalto', '#3C3C3C', [
    'Cinza muito escuro, quase preto, a cor do asfalto novo.',
    'Mais claro que o preto carvão e mais escuro que o cinza fumaça.',
    'Cor de pista de corrida depois da chuva.',
    'Cor de capa de notebook escuro.',
    'Cinza de carvão queimado esfriando na grelha.',
  ]),
  colorHex('Cinza Esverdeado Escuro', '#2F4F4F', [
    'Cinza escuro com um fundo verde-azulado, a cor de pedra molhada coberta de limo.',
    'Mais escuro e mais verde que o cinza chumbo.',
    'Cor de lousa de restaurante escrita a giz.',
    'Cor de mata escura vista de longe em dia de chuva.',
    'Verde quase preto de capa de livro de capa dura.',
  ]),
  colorHex('Preto', '#000000', [
    'O preto total, sem nenhum reflexo nem tom de outra cor, escuridão absoluta.',
    'Cor de tela de celular desligado sem reflexo.',
    'Preto de noite sem lua e sem poste de luz.',
    'Mais escuro que o carvão e sem nada de azul ou marrom escondido.',
    'Cor de fundo de cinema antes de o filme começar.',
  ]),
  colorHex('Branco Puro', '#FFFFFF', [
    'O branco total, sem nenhum tom de outra cor, a folha de papel nova.',
    'Cor de tela de celular acesa com o fundo claro.',
    'Branco de parede de museu de arte contemporânea.',
    'Mais claro que qualquer outra cor da paleta.',
    'Cor de louça de restaurante chique antes de a comida chegar.',
  ]),
  colorHex('Branco Neve', '#FFFAFA', [
    'Branco com um sopro de rosado, a cor da neve fresca ao amanhecer.',
    'Quase o branco puro, só com um pingo de quente.',
    'Cor de lençol de hotel de luxo bem passado.',
    'Branco de vestido de noiva em foto de revista.',
    'Cor de sorvete de coco quando o pote acabou de abrir.',
  ]),
  colorHex('Branco Fumaça', '#F5F5F5', [
    'Cinza claríssimo, quase branco, a cor da fumaça de vela bem diluída.',
    'Mais escuro que o branco puro e mais claro que o cinza neblina.',
    'Cor de parede de escritório moderno.',
    'Cor de camiseta branca já lavada várias vezes.',
    'Cor de fundo de site de empresa de tecnologia.',
  ]),
  colorHex('Limão Pastel', '#FAFAD2', [
    'Amarelo muito clarinho e suave, quase um branco amanteigado.',
    'Mais pálido que o amarelo pastel, com cara de bolo de limão.',
    'Cor de glacê de sorvete de limão com leite condensado.',
    'Cor de pétala de margarida iluminada de lado.',
    'Cor de lençol de bebê em tom de manteiga.',
  ]),
  colorHex('Baunilha', '#F3E5AB', [
    'Amarelo suave e cremoso, a cor do sorvete de baunilha derretendo.',
    'Mais amarelo que o creme e mais claro que a manteiga.',
    'Cor de pudim de leite antes de pôr a calda.',
    'Cor de massa de bolo de baunilha antes de assar.',
    'Cor de papel de carta antigo guardado numa gaveta.',
  ]),
  colorHex('Água de Coco', '#D9F1EB', [
    'Verde-azulado muito clarinho e leitoso, a cor da água de coco gelada.',
    'Mais pálido que a menta pastel, com cara de bebida de praia.',
    'Cor de lençol de spa em tom de água.',
    'Cor de sabão em barra de hotel de praia.',
    'Branco esverdeado de sorvete de coco com hortelã.',
  ]),
  colorHex('Chantilly', '#FFFDF5', [
    'Branco levemente amanteigado, a cor do chantilly fresco.',
    'Mais quente que o branco puro e mais claro que o marfim.',
    'Cor de claras em neve batidas até o ponto.',
    'Cor de espuma de cappuccino logo depois de servida.',
    'Cor de parede branca de casa de praia, com um pouco de sol.',
  ]),
  colorHex('Leite', '#FDFFF5', [
    'Branco levemente esverdeado e leitoso, a cor do copo de leite.',
    'Quase igual ao chantilly, só um pouquinho mais fresco e mais frio.',
    'Cor de iogurte natural em potinho.',
    'Cor de espuma de sabão de leite de rosas.',
    'Cor de louça branca com um leve reflexo esverdeado.',
  ]),
  colorHex('Nuvem', '#EEF2F7', [
    'Branco azulado e suave, a cor de uma nuvem alta num dia de céu claro.',
    'Mais frio que o branco fumaça e mais azulado que o gelo.',
    'Cor de parede de quarto de bebê em tom frio.',
    'Cor de lençol de hospital novo em tom azulado.',
    'Cor de papel de embalagem de remédio, azulado e limpo.',
  ]),
  colorHex('Tempestade', '#5B6770', [
    'Cinza azulado escuro, a cor do céu pouco antes de a tempestade cair.',
    'Mais claro que o chumbo e mais frio que o cinza médio.',
    'Cor de nuvem carregada em dia de chuva forte.',
    'Cor de telhado de zinco molhado.',
    'Cor de capa de chuva de pescador de filme.',
  ]),
  colorHex('Mármore', '#E8E4DC', [
    'Branco amarelado com fundo cinza, a cor do mármore branco polido.',
    'Mais escuro que o osso e mais quente que o branco fumaça.',
    'Cor de balcão de cozinha de apartamento chique.',
    'Cor de estátua de museu iluminada por luz de teto.',
    'Cor de piso de hotel antigo muito bem cuidado.',
  ]),
  colorHex('Cinza Fogueira', '#B2BEB5', [
    'Cinza claro e esverdeado, a cor das cinzas depois que a fogueira apaga.',
    'Mais verde que o cinza fosco e mais claro que a pedra.',
    'Cor de chá de camomila já frio no fundo da xícara.',
    'Cor de folha de oliveira seca ao sol.',
    'Cor de poeira de estrada de terra batida.',
  ]),
];
