import { color, type PaletteColor } from './palette-types';

/** Neutros, escuros, terrosos e pastéis. */
export const PALETTE_4: PaletteColor[] = [
  color('Branco Gelo', 210, 4, 98, [
    'Branco puro com um sopro frio, cor de geladeira nova.',
    'Quase sem cor nenhuma, mas ainda sem chegar ao cinza.',
    'Brilho altíssimo e saturação quase zero: limpo como papel de impressora.',
    'Cor de parede de clínica estética que cobra caro.',
    'Branco que fica estranho ao lado de qualquer outro branco.',
    'Cor de camiseta lisa que ninguém lembra de ter comprado.',
    'Parece neve que ainda não foi pisada.',
    'Mais frio que o off-white e mais claro que qualquer cinza.',
    'Branco de louça de restaurante com muitos talheres.',
  ]),
  color('Off-White', 45, 8, 97, [
    'Branco com um toque amarelado, de papel de caderno antigo.',
    'Brilho altíssimo e um fio de calor: nem frio, nem puro.',
    'Cor de parede de casa de campo que ninguém repinta há anos.',
    'Mais amarelado que o branco gelo e bem menos creme que o marfim.',
    'Cor de lençol de algodão lavado cem vezes.',
    'Branco de vestido de noiva que não quer parecer branco demais.',
    'Cor de tinta de teto de apartamento alugado.',
    'Quase branco, mas com um segredinho quente.',
    'Cor de xícara de café com leite que sobrou na pia.',
  ]),
  color('Marfim', 55, 12, 100, [
    'Branco levemente amarelado de tecla de piano e de dente de elefante.',
    'Brilho máximo e saturação baixa, puxando para o creme.',
    'Cor de convite de casamento que custou uma fortuna.',
    'Mais quente que o off-white e menos amarelo que o creme.',
    'A cor das teclas brancas depois de muitos anos de uso.',
    'Cor de renda de vestido da bisavó.',
    'Delicado, antigo e elegante.',
    'Cor de papel de carta que a tia ainda usa.',
    'Branco com cara de coisa herdada.',
  ]),
  color('Cinza Claro', 0, 0, 85, [
    'Cinza bem claro, quase prata, sem nenhum tom de cor.',
    'Brilho alto e saturação zero: neutro de verdade.',
    'Cor de parede de escritório de empresa de médio porte.',
    'Mais claro que o cinza médio e menos frio que o prata.',
    'Cor de calçada limpa em manhã nublada.',
    'Cinza de nuvem fina que não vai chover.',
    'Cor de moletom que combina com tudo e ninguém nota.',
    'Neutro, calmo e sem personalidade.',
    'Cor de caixa de equipamento que o técnico traz.',
  ]),
  color('Cinza Concreto', 40, 6, 62, [
    'Cinza de concreto aparente, levemente quente e meio sujo.',
    'Brilho médio e uma gota de bege escondida no cinza.',
    'Cor de parede de obra que nunca recebeu tinta.',
    'Mais quente que o chumbo e mais escuro que o cinza claro.',
    'Cor de calçada rachada de bairro antigo.',
    'Cinza de prédio comercial dos anos setenta.',
    'Cor de saco de cimento aberto e deixado na chuva.',
    'Industrial, seco e bem sem graça.',
    'Cinza que combina com poeira.',
  ]),
  color('Cinza Médio', 0, 0, 55, [
    'Cinza exatamente no meio do caminho entre branco e preto.',
    'Brilho médio e saturação zero: sem calor e sem frio.',
    'A cor de um fundo de foto de documento.',
    'Cor de asfalto novo antes de ficar preto.',
    'Neutro puro, como o céu de um dia que não resolveu o que quer ser.',
    'Cor de peça de computador que só técnico conhece.',
    'Cinza de elefante, de rinoceronte e de paciência acabando.',
    'Mais escuro que o concreto e mais claro que o chumbo.',
    'Cor do botão desabilitado do site.',
  ]),
  color('Cinza Azulado', 210, 18, 60, [
    'Cinza com um toque de azul, cor de nuvem de chuva próxima.',
    'Brilho médio e pouca saturação, mas com um frio inconfundível.',
    'Cor de terno cinza de reunião de banco.',
    'Mais frio que o cinza médio e mais claro que o chumbo.',
    'Cinza de mar em dia de ressaca.',
    'Cor de ardósia, daquela pedra que vira lousa.',
    'Cor de céu de cidade grande em dia de garoa.',
    'Mistura de cinza com um azul que se esconde.',
    'Cor de capa de notebook que quer parecer executiva.',
  ]),
  color('Prata', 210, 6, 78, [
    'Cinza claro com brilho frio de metal polido.',
    'Quase sem cor, mas levemente azulado como aço novo.',
    'Cor de talher bom que só sai em ocasião especial.',
    'Mais claro que o cinza azulado e mais frio que o cinza claro.',
    'Cor de lata de refrigerante fosca.',
    'Cinza de medalha de segundo lugar.',
    'Cor de panela de aço inox que ainda não foi riscada.',
    'Brilho alto e saturação baixíssima: neutro com ar de luxo.',
    'Cor de lua cheia quando não está nenhuma neblina.',
  ]),
  color('Cinza Chumbo', 210, 10, 35, [
    'Cinza escuro e pesado, cor de metal que afunda na água.',
    'Brilho baixo e saturação baixa, com um sopro de azul.',
    'Cor de céu de tempestade antes da primeira trovoada.',
    'Mais escuro que o cinza azulado e mais claro que o grafite.',
    'Cor de capa de computador que o técnico de informática recomenda.',
    'Cinza de panela de ferro que passou pelo fogão a lenha.',
    'Cor de asfalto molhado à noite.',
    'Sério, silencioso e meio sombrio.',
    'Cor de terno de pessoa que fala baixo e manda em tudo.',
  ]),
  color('Grafite', 220, 12, 25, [
    'Cinza quase preto, cor de lápis de desenhista.',
    'Brilho baixíssimo e um frio quase imperceptível no meio.',
    'Cor de lousa de sala de aula depois de apagada.',
    'Mais escuro que o chumbo e mais claro que o preto carvão.',
    'Cor de carcaça de aparelho eletrônico caro.',
    'Cor de fundo de aplicativo que se diz sofisticado.',
    'Grafite de mina de lapiseira, só que muito mais grosso.',
    'Cinza que parece preto até alguém acender uma luz.',
    'Cor de capa de celular que combina com tudo e nada.',
  ]),
  color('Preto Carvão', 0, 0, 12, [
    'Preto quase absoluto, só um pouquinho acima do escuro total.',
    'Brilho baixíssimo e saturação zero: não tem dica de cor nenhuma.',
    'A cor do carvão do churrasco antes de acender.',
    'Cor de tela de TV desligada em sala escura.',
    'Preto de roupa de festa em que ninguém quer errar.',
    'Cor de gato preto passando atrás da cortina.',
    'Preto que não é puro, mas quase convence.',
    'Cor de capa de livro de terror pesado.',
    'Escuro demais para ter apelido.',
  ]),
  color('Ébano', 30, 30, 18, [
    'Preto com um fundo marrom de madeira escura e densa.',
    'Brilho baixíssimo e um calor discreto escondido no escuro.',
    'Cor de piano de cauda de sala de concerto.',
    'Mais quente que o carvão e mais escuro que o chocolate.',
    'A cor da madeira de móvel de escritório muito antigo.',
    'Cor de caixa de charuto vazia.',
    'Preto com cheiro de biblioteca e verniz.',
    'Cor de café passado sem açúcar e sem remorso.',
    'Cor de coronel de filme de faroeste.',
  ]),
  color('Marrom Chocolate', 20, 70, 30, [
    'Marrom escuro e intenso, cor de chocolate meio amargo.',
    'Brilho baixo e saturação alta: um marrom que parece derreter.',
    'Cor de barra de chocolate com muito cacau.',
    'Mais avermelhado que o ébano e mais escuro que o café.',
    'Cor de brownie ainda quente no meio.',
    'Marrom de sofá de couro de escritório de advogado.',
    'Cor de calda de sorvete que escorre devagar.',
    'Cor de ganache de bolo de aniversário bem feito.',
    'Escuro, doce e perigoso para a dieta.',
  ]),
  color('Marrom Café', 25, 60, 40, [
    'O marrom do café coado na hora, forte e de cheiro bom.',
    'Brilho médio-baixo e saturação média-alta: terroso e acolhedor.',
    'Cor de grão torrado esperando a máquina.',
    'Mais claro que o chocolate e mais escuro que a madeira.',
    'Cor de borra de café na xícara, depois da fofoca.',
    'Cor de parede de cafeteria que quer parecer aconchegante.',
    'Marrom que acorda sem precisar de despertador.',
    'Cor de bota de trabalho que já andou muito.',
    'Quente, escuro e cheio de energia.',
  ]),
  color('Marrom Madeira', 25, 65, 55, [
    'Marrom médio de madeira de lei, daquelas de móvel pesado.',
    'Brilho médio e saturação média-alta: calor de cabana.',
    'Cor de mesa de jantar de família grande.',
    'Mais claro que o café e mais quente que a castanha.',
    'Cor de cabo de ferramenta usado há décadas.',
    'Cor de porta de casa de vilarejo.',
    'Marrom de violão antigo bem cuidado.',
    'Cor de banco de praça que ninguém tem coragem de pichar.',
    'Parece cheirar a serragem só de olhar.',
  ]),
  color('Castanha', 15, 55, 35, [
    'Marrom avermelhado e escuro, cor de castanha assada no Natal.',
    'Brilho baixo e saturação média: um marrom com um fio de ferrugem.',
    'Cor de cabelo castanho escuro de quem acabou de pintar.',
    'Mais avermelhado que o café e menos preto que o ébano.',
    'Cor de casca de castanha-do-pará depois de aberta.',
    'Cor de móvel de mogno bem lustrado.',
    'Marrom de casca de árvore em dia úmido.',
    'Cor de couro de carteira velha que ainda funciona.',
    'Escura, quente e com certo ar de outono.',
  ]),
  color('Bege', 40, 20, 92, [
    'Marrom clarinho, quase creme, cor de areia seca e de parede de sala.',
    'Brilho alto e saturação baixa: o neutro mais quente de todos.',
    'Cor de sofá que todo mundo escolhe para não errar.',
    'Mais claro e mais rosado que o cáqui.',
    'Cor de capa de trench coat de filme de espionagem.',
    'Cor de parede de consultório que quer acalmar.',
    'Bege de esparadrapo que não combina com ninguém.',
    'Neutro, seguro e um pouco sem ousadia.',
    'Cor de biscoito de maisena logo depois de sair do pacote.',
  ]),
  color('Cáqui', 45, 30, 76, [
    'Bege esverdeado de calça de explorador e de uniforme de safári.',
    'Brilho médio-alto e saturação baixa: um terra com ar de aventura.',
    'Cor de chapéu de aventureiro que nunca viajou.',
    'Mais escuro e mais amarelado que o bege.',
    'Cor de mochila de excursão escolar.',
    'Cor de poeira de estrada de terra batida.',
    'Cor de bermuda de homem que sempre diz que ama praia.',
    'Marrom claro com uma pitada de oliva escondida.',
    'Cor de caderneta de campo com folhas de papel pardo.',
  ]),
  color('Nude', 25, 22, 90, [
    'Rosado-bege de tom de pele clara, cor de esmalte discreto.',
    'Brilho alto e saturação baixa: neutro com um sopro de rosa.',
    'Cor de sapatilha de ballet que combina com qualquer roupa.',
    'Mais rosado que o bege e mais claro que o café com leite.',
    'Cor de batom que diz "não estou de batom".',
    'Cor de lingerie em vitrine de loja de departamento.',
    'Neutro quente que quase some contra a pele.',
    'Cor de band-aid antigo, antes de ele ter várias opções.',
    'Cor de parede de salão de maquiagem.',
  ]),
  color('Café com Leite', 28, 35, 75, [
    'Marrom claro e cremoso, o tom exato do café com muito leite.',
    'Brilho médio-alto e saturação média-baixa: quente e suave.',
    'Cor de capuccino com espuma, antes de mexer.',
    'Mais escuro que o bege e mais claro que a madeira.',
    'Cor de sofá de bar que mantém a sujeira disfarçada.',
    'Cor de calda de doce de leite que acabou de esfriar.',
    'Marrom pálido e confortável, como suéter de lã grossa.',
    'Cor de cachorro caramelo dormindo no sol.',
    'Mistura boa entre o café da manhã e a hora da sesta.',
  ]),
  color('Sálvia', 100, 22, 70, [
    'Verde acinzentado e suave, cor da folha de sálvia seca.',
    'Brilho médio-alto e saturação baixa: um verde de planta de cozinha.',
    'Cor de parede de casa de campo moderna.',
    'Mais cinza que o verde menta e mais verde que o cinza azulado.',
    'Cor de tempero de assado do domingo.',
    'Cor de móvel de cozinha escandinava.',
    'Verde de chá de ervas em xícara de cerâmica.',
    'Cor de almofada de decoração de loja minimalista.',
    'Natural, discreto e com cara de saúde.',
  ]),
  color('Verde Garrafa', 150, 85, 28, [
    'Verde escuro e fechado, cor do vidro de garrafa de vinho.',
    'Brilho baixíssimo e saturação alta: quase preto, mas ainda verde.',
    'Cor de poltrona de clube inglês onde ninguém fala alto.',
    'Mais escuro que a floresta e mais azulado que o musgo.',
    'Cor de vidro de remédio antigo na estante da avó.',
    'Cor de capa de livro de capa dura em biblioteca.',
    'Verde de folha de pinheiro à meia-noite.',
    'Cor de cortina de teatro de ópera.',
    'Verde que diz "sim, eu sei o que estou fazendo".',
  ]),
  color('Verde Pastel', 125, 25, 95, [
    'Verde bem clarinho e suave, de pastel de confeitaria.',
    'Brilho altíssimo e saturação baixa: é como uma folha lavada em leite.',
    'Cor de glacê de bolo de chá de bebê.',
    'Mais amarelado que a menta e mais claro que o pistache.',
    'Cor de gominha de maçã verde de saquinho de festa.',
    'Verde de cortina de berçário.',
    'Cor de plástico de brinquedo de criança pequena.',
    'Delicado, fresco e inofensivo.',
    'Cor de bala de menta que ninguém reclama de pegar.',
  ]),
  color('Amarelo Pastel', 55, 25, 100, [
    'Amarelo clarinho e macio, cor de manteiga fresca.',
    'Brilho máximo e saturação baixa: um amarelo de leve.',
    'Cor de glacê de cupcake em chá de bebê.',
    'Mais pálido que o creme e mais vivo que o branco.',
    'Cor de pintinho recém-nascido.',
    'Cor de lençol de berço com bolinhas.',
    'Cor de gominha de abacaxi que ninguém escolhe primeiro.',
    'Doce, calmo e feito para parecer feliz.',
    'Amarelo de sol de manhã cedinho, ainda sem força.',
  ]),
  color('Azul Pastel', 215, 25, 100, [
    'Azul bem clarinho e delicado, de céu de desenho de bebê.',
    'Brilho máximo e saturação baixa: um azul de algodão.',
    'Cor de glacê de bolo de menino em chá de bebê.',
    'Mais forte que o azul gelo e mais claro que o céu.',
    'Cor de roupinha de enxoval de neném.',
    'Cor de camiseta polo que combina com tudo no escritório.',
    'Azul macio de sonho de criança.',
    'Cor de fundo de aplicativo de bem-estar.',
    'Azul que não quer incomodar ninguém.',
  ]),
  color('Laranja Pastel', 28, 28, 100, [
    'Laranja clarinho e suave, quase um pêssego pálido.',
    'Brilho máximo e saturação baixa: um alaranjado fofo.',
    'Cor de glacê de cenoura sem a cenoura.',
    'Mais pálido que o damasco e mais quente que o creme.',
    'Cor de sorvete de creme de laranja derretendo.',
    'Cor de babado de roupa infantil de verão.',
    'Cor de manhã de sol que ainda está bocejando.',
    'Doce, quente e gostoso de olhar.',
    'Cor de gominha de tangerina de saquinho de festa.',
  ]),
  color('Menta Pastel', 160, 15, 100, [
    'Verde-azulado clarinho, quase branco, de bala de menta suave.',
    'Brilho máximo e saturação muito baixa: um sopro de verde gelado.',
    'Cor de sorvete de hortelã com chocolate branco.',
    'Mais pálido e mais azulado que o verde pastel.',
    'Cor de lençol de hotel de luxo que ninguém ousa sujar.',
    'Cor de parede de clínica de dentista infantil.',
    'Verde que pede para ser abraçado.',
    'Frio, limpo e muito suave.',
    'Cor de espuma de sabão de menta.',
  ]),
  color('Greige', 35, 12, 72, [
    'Meio cinza, meio bege, daí o nome: o neutro que ninguém sabe definir.',
    'Brilho médio-alto e saturação bem baixa, com um fundo quente.',
    'Cor de parede de apartamento recém-reformado por arquiteto.',
    'Mais quente que o cinza claro e menos amarelo que o bege.',
    'Cor de sofá de linho que combina com decoração escandinava.',
    'Cor de pedra de calçada de rua de pedestres.',
    'Cor de peça de roupa que a loja chama de "tom natural".',
    'Neutro elegante que fica bem em qualquer coisa.',
    'Cor de pelo de gato cinza de tom quente.',
  ]),
];
