import { color, type PaletteColor } from './palette-types';

/** Quentes: vermelhos, laranjas e amarelos. */
export const PALETTE_1: PaletteColor[] = [
  color('Vermelho Tomate', 7, 85, 90, [
    'A cor do tomate maduro, aquele que você deixa na fruteira até alguém reclamar.',
    'Vermelho de verdade, com um fio de laranja: nem sangue, nem morango.',
    'Se o ketchup tivesse vergonha, ficaria dessa cor.',
    'Bem vivo e forte, mas ainda alegre, longe do vermelho escuro de vinho.',
    'A bolinha vermelha do nariz de palhaço, só que um tico mais fosca.',
    'Cor de bochecha depois de subir três lances de escada.',
    'Aquele vermelho de placa de pare, mas com cara de quem acabou de sair da horta.',
    'Saturação lá em cima, brilho alto: é o vermelho que grita sem ser agressivo.',
    'Pizza de domingo antes de entrar no forno: o molho é exatamente isso.',
  ]),
  color('Vermelho Sangue', 355, 90, 65, [
    'A cor do sangue que escorre em filme de terror, escurinho e pesado.',
    'Vermelho fechado, quase marrom de tão escuro, mas ainda vermelho.',
    'Cor da capa de vampiro que se leva a sério.',
    'Brilho médio para baixo: imagine um vermelho que passou a noite sem dormir.',
    'Não é rosado nem alaranjado, puxa levemente para o lado do vinho.',
    'A cor de um machucado fresco: forte, sério, sem brincadeira.',
    'Se um tomate passasse anos em terapia, ficaria assim.',
    'Cor de cortina de teatro antiga, daquelas pesadas de veludo.',
    'Muito saturado e escuro: o oposto de um vermelho de bala.',
  ]),
  color('Carmim', 348, 90, 75, [
    'Carmim é o vermelho dos tapetes de gala, um pouco rosado por dentro.',
    'Vermelho profundo, com um sopro de rosa que o separa do vermelho de fogo.',
    'A cor do batom de quem chega por último e rouba a cena.',
    'Cor de rosa velha: vermelho que quase virou magenta, mas desistiu.',
    'Entre o sangue e a cereja: forte, escuro e elegante.',
    'O vermelho de uma maçã do amor depois que o açúcar esfria.',
    'Bem saturado, brilho médio-alto, levemente frio, sem nada de laranja.',
    'A cor de um coração desenhado com muita convicção.',
    'Pense num vermelho chique, daqueles que pedem um terno preto ao lado.',
  ]),
  color('Cereja', 345, 85, 70, [
    'A cor da cereja do bolo, aquela que ninguém quer dividir.',
    'Vermelho meio arroxeado, escuro e brilhante, como fruta envernizada.',
    'Quase vinho, só que ainda com pressa de ser fruta.',
    'Cor de cereja de coquetel: exageradamente vermelha e um pouco falsa.',
    'Mais fria que um tomate, mais escura que um morango.',
    'Se você apertasse uma cereja, o que escorre é essa cor.',
    'Saturação alta e brilho de médio para baixo: é vermelho com pitada de roxo.',
    'A cor do sorvete de cereja derretido na calçada.',
    'Cor de maçã do rosto de quem tomou vinho tinto demais.',
  ]),
  color('Morango', 350, 75, 92, [
    'Morango fresquinho: vermelho claro, meio rosado, com brilho de fruta lavada.',
    'Vermelho alegre e suave, longe de qualquer coisa escura ou séria.',
    'A cor da calda de morango no sorvete de baunilha.',
    'Parece vermelho, mas tem um tom rosado que denuncia a sobremesa.',
    'Brilho alto, saturação boa: é um vermelho que sorri.',
    'Cor de gominha de fruta que você jura que é saudável.',
    'Mais clara que cereja e mais rosada que tomate.',
    'Pense em bochecha de criança depois de brincar no sol.',
    'O vermelho da embalagem de iogurte de morango, a que você sempre pega.',
  ]),
  color('Vinho', 345, 80, 45, [
    'A cor do vinho tinto no fundo da taça, de noite, com luz baixa.',
    'Vermelho bem escuro com um toque de roxo: sério, maduro e meio misterioso.',
    'Brilho baixo: é uma cor que pede jantar à luz de vela.',
    'Se o carmim ficasse de luto, seria isso.',
    'Cor de sofá de advogado que nunca ri no escritório.',
    'Quase bordô, mas ainda nitidamente vermelho e não marrom.',
    'Saturada e escura: lembra uva madura esquecida na geladeira.',
    'A cor da cortina do cinema antigo e do carpete do corredor do hotel.',
    'Escuríssima perto de um tomate; é o vermelho depois das dez da noite.',
  ]),
  color('Tijolo', 10, 65, 70, [
    'A cor de tijolo de obra, aquele laranja-avermelhado fosco e empoeirado.',
    'Vermelho queimado de sol, com um fundo marrom discreto.',
    'Cor de muro de casa antiga, com cara de ter história.',
    'Nem vivo nem apagado: uma cor de terra, meio seca.',
    'Telhado de casa de campo visto de longe numa tarde seca.',
    'Mistura de vermelho com marrom, sem brilho de plástico.',
    'Pense num tijolo à vista de pizzaria, o clima aconchegante de forno a lenha.',
    'Saturação média e brilho médio: terrosa, pesada e confiável.',
    'A cor do chão de quadra de saibro depois do treino.',
  ]),
  color('Ferrugem', 18, 80, 65, [
    'A cor de um portão que ninguém pintou desde 1998.',
    'Laranja escuro, queimado, com cara de metal oxidado ao tempo.',
    'Mais laranja que o tijolo, mais escuro que a cenoura.',
    'Pense em um prego esquecido na chuva por uma estação inteira.',
    'Cor de folha de outono que caiu faz uma semana.',
    'Quente, terrosa e desbotada de tanta lua e sol.',
    'Parte do caminho entre o vermelho-escuro e o marrom-alaranjado.',
    'Brilho médio-baixo, saturação alta: a cor do tempo passando.',
    'A cor da lataria de um carro antigo que ainda dá partida de teimosia.',
  ]),
  color('Coral', 10, 60, 100, [
    'Coral de aquário: laranja-rosado, vivo e meio tropical.',
    'Entre o rosa e o laranja, bem claro e luminoso.',
    'A cor do batom de verão que combina com tudo, menos com seriedade.',
    'Parece o pôr do sol numa foto de revista de viagem.',
    'Brilho no máximo: é uma cor que acende o ambiente.',
    'Se um salmão tomasse sol a tarde toda, ficaria assim.',
    'Quente, doce e alegre, sem nenhuma sombra escura nela.',
    'A cor da camisa de quem foi para a praia e voltou bronzeado.',
    'Pense num camarão cozido, só que mais alegre e menos comestível.',
  ]),
  color('Salmão', 10, 45, 98, [
    'Cor de filé de salmão cru, rosado-alaranjado e suculento.',
    'Um rosa com saudade do laranja, bem claro e macio.',
    'Fica entre o pêssego e o coral, mais para o lado rosado.',
    'A cor do sushi que você pega primeiro na esteira.',
    'Pastel quente: nada escuro, nada gritante.',
    'Pense num abajur de quarto que deixa tudo aconchegante.',
    'Cor de camiseta que todo mundo tem e diz que nunca comprou.',
    'Saturação pela metade, brilho quase no máximo.',
    'Se uma melancia fosse tímida, essa seria a cor do miolo dela.',
  ]),
  color('Laranja Cenoura', 28, 90, 95, [
    'A cor da cenoura recém-arrancada da terra e lavada na torneira.',
    'Laranja clássico, sem nada de vermelho e sem nada de amarelo demais.',
    'Cone de trânsito, só que mais apetitoso.',
    'A cor do Garfield, com direito a um pouco de preguiça.',
    'Vivo e forte: é o laranja que todo mundo pensa quando ouve a palavra laranja.',
    'Cor de colete de obra que não deixa ninguém sem ser visto.',
    'Quente, saturado e brilhante: puro laranja de desenho animado.',
    'Quando a cenoura vira bolo, a cobertura é dessa cor.',
    'Entre o tomate e o limão, bem no meio da estrada, mas puxando pro sol.',
  ]),
  color('Laranja Tangerina', 24, 95, 100, [
    'A tangerina bem madura, aquela que descasca sem briga.',
    'Laranja elétrico, saturadíssimo, quase neon sob o sol.',
    'A cor do refrigerante de laranja que sempre tem na festa.',
    'Mais forte e mais vermelha que a cenoura, bem ardente.',
    'Brilho no teto e saturação lá em cima: é a cor mais gritante do grupo.',
    'Cor de luz de semáforo quando o amarelo está fingindo ser laranja.',
    'Puro suco de laranja, sem açúcar, sem água, sem desculpa.',
    'Parece o pôr do sol de verão no meio do deserto.',
    'Se você sente o cheiro da casca quando olha, é essa.',
  ]),
  color('Abóbora', 22, 85, 85, [
    'A cor da abóbora de Halloween, antes de virar luminária.',
    'Laranja um tanto escuro, com cara de outono e sopa quente.',
    'Mais pesada que a tangerina, menos queimada que a ferrugem.',
    'Cor de suéter de vovó que você começou a gostar de repente.',
    'Brilho um pouco abaixo do máximo, mas a saturação ainda grita.',
    'Cor do purê de abóbora com um fio de azeite.',
    'Parece uma folha seca ainda bem laranja, caída no parque.',
    'Quente e firme: é um laranja de pé no chão, sem exagero de neon.',
    'A cor do bolo da cobertura que ninguém admite que adora.',
  ]),
  color('Damasco', 30, 45, 98, [
    'Cor de damasco seco: laranja claro e suave, meio rosado por dentro.',
    'Entre o pêssego e o creme, com um brilho quente.',
    'Pastel de fruta, nada de saturação exagerada.',
    'A cor de parede de sala que a decoradora chamou de "acolhedora".',
    'Mais claro que a cenoura e menos rosa que o salmão.',
    'Pense num sorvete de manga bem cremoso.',
    'Alto brilho e saturação média: uma cor para dias tranquilos.',
    'A cor do biscoito amanteigado quando sai do forno.',
    'Nuvem de fim de tarde que ainda tem um pouco de dia dentro.',
  ]),
  color('Pêssego', 25, 35, 100, [
    'O pêssego mais macio, daqueles que cabem na palma da mão.',
    'Rosado-alaranjado muito claro, quase um creme com vergonha.',
    'A cor da pele de bebê em fotos de lembrancinha.',
    'Brilho no máximo e saturação baixa: tudo suave, tudo doce.',
    'Mais claro que o salmão e mais quente que o rosa.',
    'Cor de esmalte discreto que combina com qualquer roupa.',
    'Como a casquinha de sorvete de pêssego quando molha.',
    'Pense na luz do quarto às seis da tarde, entrando pela cortina.',
    'Um tom que não grita nem sussurra: só sorri.',
  ]),
  color('Âmbar', 40, 95, 90, [
    'Âmbar é a cor da pedra que prende mosquito de dinossauro.',
    'Laranja amarelado, quente e translúcido como mel envelhecido.',
    'O semáforo no segundo exato antes de ficar vermelho.',
    'Entre a tangerina e o amarelo: bem no meio, puxando o dourado.',
    'Cor de cerveja clara ao contraluz de uma janela.',
    'Muito saturado, brilhante e profundo, como vidro de garrafa velha.',
    'A luz de uma lâmpada incandescente numa sala antiga.',
    'Quente, dourado e levemente alaranjado: nada de verde por perto.',
    'A cor do xarope de bordo escorrendo em panqueca.',
  ]),
  color('Mel', 42, 85, 90, [
    'A cor do mel escorrendo da colher no pão quente.',
    'Dourado-escuro, grosso e brilhante, sem nada de vermelho.',
    'Entre o âmbar e a mostarda, só que bem mais docinho.',
    'Pense num pote de vidro de mel na prateleira da cozinha.',
    'Amarelo laranjado quente, com saturação alta e luminosidade boa.',
    'Cor de abelha vista de longe com a luz do sol atrás.',
    'Se o ouro fosse comestível, teria esse tom.',
    'Cor de madeira clara envernizada de um móvel bonito.',
    'Doce e quente: a cor que dá vontade de lamber.',
  ]),
  color('Mostarda', 48, 90, 80, [
    'A cor da mostarda do cachorro-quente, a que só tem mostarda.',
    'Amarelo escuro e esverdeado, com cara de molho de lanchonete.',
    'Mais pesada e menos alegre que o limão, bem sóbria.',
    'Amarelo que viveu um pouco: nada de neon, nada de bebê.',
    'Cor de sofá retrô dos anos setenta, perfeita para filme de época.',
    'Brilho médio-alto, mas com uma sombra marrom por baixo.',
    'Pense no suéter de professor de literatura que adora citar autor russo.',
    'Entre o dourado e o oliva, bem para o lado amarelo.',
    'A cor do curry em pó sob a luz do sol da cozinha.',
  ]),
  color('Amarelo Gema', 42, 88, 98, [
    'Gema de ovo mole, aquela que escorre quando você corta.',
    'Amarelo-alaranjado, vivo e cremoso, com brilho de gordura boa.',
    'Mais laranja que o limão, mais amarelo que a tangerina.',
    'A cor do miolo do ovo frito num domingo preguiçoso.',
    'Quente, forte e brilhante: é o amarelo mais comestível que existe.',
    'Imagine o sol desenhado por uma criança com giz de cera.',
    'Pense na cor de gema que a galinha do sítio conseguiu, com milho de verdade.',
    'Saturado e iluminado, sem sombra nenhuma de escuro.',
    'Cor da massa de pastel antes de fritar, com ovo na receita.',
  ]),
  color('Amarelo Limão', 55, 85, 98, [
    'A casca do limão-siciliano, azedinho só de olhar.',
    'Amarelo frio, esverdeado, vibrante e cheio de ácido.',
    'Quase neon, quase marca-texto, mas ainda fruta.',
    'Mais para o verde que a gema, mais ácido que a banana.',
    'Cor de limonada gelada num dia de calor insuportável.',
    'O amarelo que te acorda sem precisar de café.',
    'Brilho altíssimo e um pingo de verde escondido no fundo.',
    'A cor do caderno de anotações que tem aquele marca-texto fluorescente.',
    'Se você fez careta ao olhar, acertou.',
  ]),
  color('Amarelo Banana', 50, 60, 100, [
    'A casca da banana-prata madura, ainda sem as pintinhas.',
    'Amarelo claro, macio e meio pastel, bem amigável.',
    'Mais suave que o limão e menos alaranjado que a gema.',
    'Cor de pelúcia de patinho de borracha de banho.',
    'Brilho no teto e saturação média: é um amarelo doce, sem azedume.',
    'A cor da massa do pão de ló quando você olha pela janelinha do forno.',
    'Pense num post-it amarelo, só que mais quentinho.',
    'O amarelo de cartilha infantil, o que ensina a letra A.',
    'Simpático, claro e confiável: é o amarelo de quem sorri na foto.',
  ]),
  color('Amarelo Canário', 54, 80, 100, [
    'A cor do canário cantando na gaiola da varanda do vizinho.',
    'Amarelo puro e brilhante, sem laranja, sem verde, sem frescura.',
    'O amarelo clássico de lápis amarelo número dois.',
    'Brilho no máximo e muita saturação: um sol de bolso.',
    'Cor de capa de chuva de criança que adora poça.',
    'O amarelo da plaquinha de "piso molhado" quando acabou de limpar.',
    'Entre a banana e o limão: exato, limpo e alegre.',
    'Parece o brinquedo da infância que tinha pintura de boa qualidade.',
    'O amarelo que a gente desenha quando faz o sol do desenho.',
  ]),
  color('Amarelo Milho', 48, 75, 100, [
    'Milho verde cozido na água, daquele de barraquinha de rua.',
    'Amarelo cremoso, quente, com um fio de dourado.',
    'Mais quente que a banana e mais claro que a gema.',
    'Pense em pipoca amanteigada antes de estourar.',
    'Cor de cabelo de boneca antiga, loiro-sol.',
    'Brilho máximo, saturação boa: bonito e comestível.',
    'A cor da canjica doce numa festa junina de bairro.',
    'Ligeiramente alaranjado, mas ainda inocente e amarelo.',
    'Se o sol de domingo virasse comida, seria essa.',
  ]),
  color('Ouro', 46, 85, 85, [
    'A cor da medalha de primeiro lugar, sem o reflexo brilhante.',
    'Amarelo escuro e rico, como metal precioso fosco.',
    'Dourado profundo, mais escuro que a mostarda e mais quente que o mel.',
    'A cor da coroa do rei que nunca perdeu uma guerra.',
    'Cor de moldura antiga de quadro em museu chique.',
    'Entre o âmbar e o amarelo, sempre sério e nobre.',
    'Pense numa corrente de ouro de vovô que ele jura que é herança.',
    'Brilho acima da média, saturação alta: luxo na medida certa.',
    'A cor do fundo dos ícones das igrejas barrocas.',
  ]),
  color('Creme', 48, 30, 100, [
    'A cor do creme de leite chantilly antes de bater.',
    'Amarelo quase branco, bem claro, com um tom manteiga.',
    'Parede de apartamento que ninguém quis arriscar com cor.',
    'Papel de carta antigo, daquele que a vovó guardava na caixa.',
    'Brilho no máximo, saturação baixíssima: quase papel de caderno.',
    'Um bege que ainda lembra que um dia foi amarelo.',
    'Cor de casquinha clara de sorvete de baunilha.',
    'Suave e acolhedor: cabe em qualquer cantinho.',
    'Pense em marshmallow ao lado de uma xícara de leite.',
  ]),
  color('Areia', 38, 35, 85, [
    'Areia da praia seca, a que gruda no pé molhado.',
    'Bege amarelado, fosco e suave, meio rosado.',
    'Cor de duna ao meio-dia sem nuvem no céu.',
    'Mais escura que o creme, mais clara que o caramelo.',
    'Pense numa bermuda de linho que combina com tudo.',
    'Saturação baixa, brilho alto: um tom natural e discreto.',
    'A cor da toalha de praia que você jura que nunca esquece.',
    'Como a casca do pão italiano quando está quase branco.',
    'Um marrom que ainda não decidiu se vai ser marrom.',
  ]),
  color('Caramelo', 30, 75, 70, [
    'Calda de caramelo no pudim, no ponto mais queimadinho.',
    'Marrom alaranjado, quente e brilhante, com cheiro de açúcar queimado.',
    'Cor da pelagem do cachorro caramelo, o orgulho nacional.',
    'Mais pesado que o mel e mais claro que o chocolate.',
    'Pense num couro de bolsa envelhecido com muito carinho.',
    'Brilho médio, saturação alta: puro doce de leite fervido.',
    'A cor do bolo de cenoura depois que a cobertura derrete.',
    'Entre o laranja e o marrom, sem escolher lado.',
    'Cor de torrada que quase passou do ponto, mas ainda é perfeita.',
  ]),
  color('Terracota', 14, 60, 72, [
    'Vaso de barro no jardim, aquele laranja-avermelhado que respira.',
    'Cor de telha nova, sem brilho nenhum, rústica e quente.',
    'Mais apagada que a ferrugem e mais suave que o tijolo.',
    'Pense numa parede de casa de praia no interior do Mediterrâneo.',
    'Barro queimado ao sol, com cara de artesanato de feira.',
    'Saturação média e brilho médio: é terra, é calor, é casa.',
    'A cor do chão de uma cozinha de fazenda.',
    'Rosa queimado e laranja sujo juntos, em harmonia.',
    'Cor de panela de barro onde a moqueca fervia.',
  ]),
  color('Pimentão Vermelho', 3, 90, 80, [
    'Pimentão vermelho cortado ao meio, cheio de brilho e de sementes.',
    'Vermelho forte, quase sem laranja, bastante saturado.',
    'Mais escuro que o tomate e mais vivo que o vinho.',
    'A cor do carro esportivo que o vizinho chama de "meu bebê".',
    'Brilho acima da média: nem fosco nem escuro demais.',
    'Cor de gorro de Papai Noel de loja de shopping.',
    'Um vermelho "pé no acelerador", sem pedir licença.',
    'Pimentão assado na churrasqueira com azeite e alho.',
    'Pense em extintor de incêndio visto de perto.',
  ]),
  color('Framboesa', 335, 75, 80, [
    'Framboesa esmagada numa torrada, rosada e meio roxa.',
    'Vermelho puxado para o magenta, escuro e frutado.',
    'Mais fria que a cereja, mais rosa que o vinho.',
    'Cor de geleia caseira com sementinhas dentro.',
    'Saturação alta, brilho médio: forte, doce e azedinha.',
    'Imagine um batom escuro de inverno que combina com casaco longo.',
    'Entre a pitaya e o morango, mas com mais atitude.',
    'A cor do sorvete de framboesa derretendo na casquinha.',
    'Se um hibisco fosse comestível, teria essa cor.',
  ]),
  color('Goiaba', 355, 50, 95, [
    'Miolo da goiabada, aquele rosa meio alaranjado e macio.',
    'Rosa-salmão, doce e quente, com cara de sobremesa de vó.',
    'Mais rosada que o coral, mais vermelha que o salmão.',
    'A cor da polpa de goiaba vermelha cortada ao meio.',
    'Brilho alto e saturação média: suave, mas com bastante alma.',
    'Cor de bochecha de boneca de porcelana.',
    'Pense num suco de goiaba gelado num dia de calor.',
    'Rosa-vermelho pastel, com um fundo cálido e doce.',
    'Doce de goiaba com queijo: o rosa é esse.',
  ]),
  color('Laranja Queimado', 16, 85, 90, [
    'Laranja que ficou tempo demais no sol e ganhou personalidade.',
    'Mais vermelho que a tangerina, mais vivo que a ferrugem.',
    'A cor de um pôr do sol no deserto, quando o céu está pegando fogo.',
    'Pense num cone de trânsito que levou umas semanas de chuva.',
    'Laranja avermelhado, forte e saturado, com chama por dentro.',
    'Cor de brasa que ainda não apagou na churrasqueira.',
    'Mais escuro que a cenoura e muito mais quente que o tijolo.',
    'A cor da camisa laranja do time que sempre quase ganha.',
    'Acesa e pesada, como o fim de tarde em março.',
  ]),
  color('Páprica', 8, 80, 72, [
    'A páprica doce no pote da cozinha, aquele pó avermelhado.',
    'Vermelho-alaranjado escuro, fosco, com cara de tempero.',
    'Meio caminho entre o tijolo e o pimentão.',
    'Cor do chouriço fatiado numa tábua de frios.',
    'Saturação alta e brilho médio-baixo: uma cor de cozinha.',
    'Pense em batata frita bem temperada, com aquele pozinho vermelho.',
    'Mais terrosa que o tomate e mais viva que o barro.',
    'A cor do molho de churrasco que ninguém conhece a receita.',
    'Quente e sério: o vermelho dos temperos que coram o prato.',
  ]),
  color('Rubi', 350, 92, 70, [
    'A pedra do anel de noivado de quem tem bom gosto.',
    'Vermelho profundo, saturado e brilhante, com um toque rosado.',
    'Mais vibrante que o vinho e mais escuro que o carmim.',
    'A cor da joia mais cara da vitrine, sob a luz certa.',
    'Intenso e luminoso: o vermelho que merece uma caixinha de veludo.',
    'Pense em vinho do porto girando devagar na taça.',
    'Cor de laço de presente de Natal chique.',
    'Um vermelho que não é sangue nem tomate: é joia.',
    'Brilho médio-alto, saturação quase no máximo.',
  ]),
  color('Mamão', 24, 65, 98, [
    'O miolo do mamão papaia, laranja alaranjado e cremoso.',
    'Laranja claro com um fundo rosado, suave e fresco.',
    'Cor de café da manhã de hotel: fruta cortada e bem arrumada.',
    'Mais claro que a cenoura, mais forte que o damasco.',
    'Saturação média e brilho altíssimo: é um laranja gentil.',
    'Pense numa vitamina de mamão com laranja no liquidificador.',
    'A cor do pôr do sol que ainda tem muito dia pela frente.',
    'Quente, suave e doce, sem nenhuma ponta de vermelho forte.',
    'Se o pêssego tivesse um primo mais animado, seria esse.',
  ]),
  color('Girassol', 50, 92, 98, [
    'A pétala de girassol virada para o sol de meio-dia.',
    'Amarelo dourado, vivo e quente, com cara de campo aberto.',
    'Entre o canário e a gema: nem verde nem laranja.',
    'Cor de quadro famoso de pintor holandês.',
    'Saturação altíssima, brilho quase máximo: um amarelo que nunca descansa.',
    'Pense no sol de manhã, no meio de um campo imenso.',
    'Um amarelo quente e generoso, com cheiro de verão.',
    'A cor do miolo de uma margarida gigante.',
    'Brilha mais que o limão e é mais doce que a mostarda.',
  ]),
];
