import { color, colorHex, type PaletteColor } from './palette-types';

/** Roxos, magentas e rosas. */
export const PALETTE_3: PaletteColor[] = [
  color('Lavanda', 260, 28, 96, [
    'Roxo bem clarinho e azulado, cor da flor de lavanda e do sachê da gaveta de roupa.',
    'Roxo tão clarinho que beira o branco, calmo, macio e perfumado.',
    'Mais azulado que o lilás e bem mais suave que o violeta.',
    'Cor de sabonete caro que ninguém usa, só deixa de enfeite.',
    'Cor do campo de flores nas fotos de viagem pela França.',
  ]),
  color('Lilás', 280, 35, 90, [
    'Roxo claro com um toque rosado, cor de flor de primavera.',
    'Cor de gominha de uva que perdeu um pouco do sabor.',
    'Mais rosado que a lavanda e mais claro que a orquídea.',
    'Lilás de papel de carta de adolescente dos anos noventa.',
    'Cor de ursinho de pelúcia vendido em shopping.',
  ]),
  color('Glicínia', 255, 35, 85, [
    'Roxo azulado e suave, cor da flor de glicínia caindo em cachos.',
    'Mais azul que o lilás e mais acinzentado que a lavanda.',
    'Cor de pergolado de casamento ao ar livre.',
    'Roxo de céu no fim da tarde, quando o laranja já foi embora.',
    'Quase um azul que está pensando em ser roxo.',
  ]),
  color('Violeta', 265, 80, 85, [
    'Roxo vivo e profundo entre o azul e o roxo, o violeta do arco-íris.',
    'Cor da flor violeta e do suco de uva concentrado.',
    'Mais azulado que o roxo uva e mais vivo que a lavanda.',
    'Cor de luz negra de balada, bem roxa.',
    'Violeta de manto de rei em peça de teatro.',
  ]),
  color('Roxo Uva', 280, 65, 55, [
    'Roxo médio e escuro, a cor da uva roxa madura, da casca ao suco.',
    'Cor de refrigerante de uva que mancha a camisa branca.',
    'Mais escuro que o violeta, mais claro que a berinjela.',
    'Cor de geleia de uva na torrada do café da manhã.',
    'Cor de língua de quem comeu muita amora.',
  ]),
  color('Roxo Berinjela', 295, 50, 32, [
    'Roxo tão escuro que parece quase preto, a casca da berinjela.',
    'Cor de sofá de veludo de sala de gente muito séria.',
    'Mais escuro que o roxo uva e mais avermelhado que o azul noite.',
    'Roxo de noite chuvosa vista da janela.',
    'Quase preto, mas com uma alma roxa escondida.',
  ]),
  color('Ameixa', 308, 55, 52, [
    'Roxo avermelhado, escuro e meio opaco, a cor da ameixa madura.',
    'Entre o roxo e o vinho, com mais rosa do que parece.',
    'Cor de batom que a tia usa em foto de formatura.',
    'Mais avermelhada que a berinjela e mais escura que a orquídea.',
    'Cor da calda de ameixa do pudim de Natal.',
  ]),
  color('Índigo', 272, 100, 52, [
    'Roxo muito intenso e escuro, entre o azul e o violeta, o sétimo degrau do arco-íris.',
    'Cor da noite quando já não é azul, mas ainda não é preto.',
    'Mais violeta que o anil e mais escuro que o roxo real.',
    'Cor de capa de feiticeiro azul-arroxeada.',
    'Cor de tinta de lula em desenho animado.',
  ]),
  color('Roxo Real', 270, 85, 65, [
    'Roxo forte e nobre, de manto de rei antigo.',
    'Roxo cheio, sem cinza, mais escuro que o violeta e mais vivo que o roxo uva.',
    'Cor de capa de livro de fantasia que a prateleira inteira ama.',
    'Cor de pacote de chocolate de marca famosa.',
    'Se o roxo precisasse de uma coroa, seria esse.',
  ]),
  color('Violeta Elétrico', 275, 90, 100, [
    'Roxo fortíssimo que parece aceso por dentro, tipo luz de LED roxa.',
    'Cor de poção mágica de desenho animado, daquelas que borbulham.',
    'Mais vivo que o violeta e mais claro que o roxo real.',
    'Roxo de neon de balada que promete uma noite longa.',
    'Cor de fundo de apresentação de empresa de tecnologia.',
  ]),
  color('Orquídea', 300, 45, 90, [
    'Roxo rosado e delicado, cor da pétala da orquídea.',
    'Entre o lilás e o rosa, com mais roxo do que rosa.',
    'Cor da orquídea que a vizinha cuida melhor que o próprio cachorro.',
    'Mais quente que o lilás e mais frio que o rosa chiclete.',
    'Rosa-lilás de papel de presente caprichado.',
  ]),
  color('Lilás Pastel', 270, 18, 100, [
    'Roxo tão claro que parece um branco com vontade de cor.',
    'Cor de glacê de bolo de aniversário infantil.',
    'Mais claro que a lavanda e muito mais suave que o lilás.',
    'Cor de ursinho de bebê que ainda não tem nome.',
    'Quase não aparece, mas dá um toque de roxo em tudo.',
  ]),
  color('Magenta', 300, 100, 90, [
    'Roxo com rosa na mesma força, o magenta da impressora.',
    'Rosa-roxo berrante, a cor mais gritante do círculo de cores.',
    'Cor de flor de cacto no deserto, que só aparece uma vez por ano.',
    'Mais roxo que o fúcsia e mais forte que a orquídea.',
    'Cor de capa de revista de moda dos anos oitenta.',
  ]),
  color('Magenta Escuro', 315, 90, 55, [
    'Rosa-roxo escuro e profundo, como suco de beterraba com uva.',
    'Cor de veludo de poltrona de teatro de ópera.',
    'Mais escuro que o magenta e mais roxo que a beterraba.',
    'Magenta fechado, de cortina de teatro em estreia.',
    'Cor de batom ousado em evento de gala.',
  ]),
  color('Fúcsia', 320, 90, 95, [
    'Rosa-roxo bem forte e luminoso, a cor da flor de brinco-de-princesa.',
    'Cor de blusa que alguém sempre usa em dia de festa junina.',
    'Mais rosa que o magenta e mais roxo que o rosa choque.',
    'Cor de bala de goma de cereja que deixa a língua pintada.',
    'Cor de cabelo de personagem de anime.',
  ]),
  color('Rosa Choque', 328, 92, 100, [
    'Rosa fortíssimo e aceso, o rosa mais berrante que existe.',
    'Cor de boneca que toda criança dos anos noventa queria ter.',
    'Mais vermelho que o fúcsia e muito mais quente que o rosa chiclete.',
    'Rosa de roupa de academia dos anos oitenta.',
    'O rosa que grita para o fundo da sala.',
  ]),
  color('Rosa Chiclete', 335, 45, 100, [
    'Rosa claro e alegre, cor de chiclete de bola de verdade.',
    'Cor de bola de chiclete prestes a estourar na cara de alguém.',
    'Mais claro que o rosa choque e mais forte que o algodão-doce.',
    'Cor de sorvete de morango com leite condensado.',
    'Rosa de pelúcia de parque de diversões.',
  ]),
  color('Rosa Algodão-Doce', 330, 22, 100, [
    'Rosa claríssimo e fofo, cor de algodão-doce de parque.',
    'Cor de bolinha de confeito no bolo de aniversário.',
    'Mais clara que o rosa chiclete e mais forte que o rosa bebê.',
    'Rosa de babado de vestido de princesa.',
    'Cor de pelúcia de coelhinho de Páscoa.',
  ]),
  color('Rosa Bebê', 345, 15, 100, [
    'Rosa quase branco, delicadíssimo, de enxoval de recém-nascido.',
    'Cor de babador e de sapatinho de tricô.',
    'Mais claro que o algodão-doce e bem mais calmo.',
    'Cor de bochecha de bebê recém-banhado.',
    'Quase não é rosa, mas ninguém duvida.',
  ]),
  color('Rosa Antigo', 350, 30, 75, [
    'Rosa acinzentado e envelhecido, como cortina de casa de campo.',
    'Cor de fotografia antiga que desbotou no álbum da avó.',
    'Mais escuro e mais apagado que o rosa chiclete.',
    'Cor de chá de rosas servido em xícara de porcelana.',
    'Cor de laço de sapatilha de balé usada muitas vezes.',
  ]),
  color('Rosa Quartzo', 340, 14, 90, [
    'Rosa fosco e suave, quase cinza, cor de pedra de quartzo rosa polida.',
    'Mais acinzentado que o rosa bebê e menos doce.',
    'Cor de esfoliante de rosto vendido em loja natural.',
    'Rosa de pele clara com um toque de blush.',
    'Cor de embalagem de produto caro que se diz minimalista.',
  ]),
  color('Rosa Flamingo', 345, 55, 100, [
    'Rosa vivo e claro, a cor das penas do flamingo.',
    'Cor de boia gigante em forma de ave na piscina.',
    'Mais quente que o chiclete e mais rosado que o coral.',
    'Cor de drinque de verão com guarda-chuvinha.',
    'Cor de bochecha corada depois de cantar em voz alta.',
  ]),
  color('Rosa Peônia', 345, 65, 95, [
    'Rosa forte e macio, de pétala de peônia cheia de camadas.',
    'Mais intenso que o flamingo e mais suave que o choque.',
    'Cor de vestido de madrinha que ninguém sabe usar de novo.',
    'Cor de torta de framboesa com creme.',
    'Rosa de jardim cuidado com muito carinho e muita regra.',
  ]),
  color('Beterraba', 335, 80, 45, [
    'Roxo avermelhado e escuro, o suco de beterraba que mancha tudo.',
    'Cor de caldo de feijão misturado com açaí.',
    'Mais escuro que a framboesa e mais rosado que o vinho.',
    'Cor da mão de quem descascou beterraba sem luvas.',
    'Cor de borra de vinho que sobrou na taça de ontem.',
  ]),
  colorHex('Roxo Clássico', '#800080', [
    'Roxo escuro e puro, entre o magenta e o violeta, a cor da fantasia de rei de carnaval.',
    'Cor de uva roxa bem madura espremida.',
    'Mais avermelhado que o violeta e mais escuro que a orquídea.',
    'Cor de manto de bruxa de desenho animado.',
    'Roxo de capa de livro de feitiços.',
  ]),
  colorHex('Roxo Rebecca', '#663399', [
    'Roxo médio e azulado, de uva roxa com um toque de violeta.',
    'Mais azulado que o roxo uva e mais escuro que o violeta.',
    'Cor de saia de menina em desenho de anos oitenta.',
    'Roxo de sombra de olho em maquiagem de show.',
    'Cor de pacote de chocolate famoso, mas com um toque de azul.',
  ]),
  colorHex('Violeta Intenso', '#9400D3', [
    'Roxo vivo e forte com um tom de azul-violeta, bem intenso.',
    'Mais claro e mais vibrante que o roxo clássico.',
    'Cor de luz violeta de bar de karaokê.',
    'Cor de poção mágica de jogo de computador.',
    'Roxo de luz de palco em show de rock.',
  ]),
  colorHex('Orquídea Intensa', '#9932CC', [
    'Roxo vivo e rosado, a orquídea mais forte e mais aberta da estufa.',
    'Mais claro e mais rosado que o roxo uva.',
    'Cor de bala de uva que mancha a língua.',
    'Roxo de ursinho de pelúcia de feira.',
    'Entre o violeta e o magenta, mais perto do violeta.',
  ]),
  colorHex('Orquídea Viva', '#BA55D3', [
    'Roxo médio e vivo com tom de rosa, a orquídea no auge da floração.',
    'Mais claro que a orquídea intensa, quase um lilás forte.',
    'Cor de glitter roxo em maquiagem de festa.',
    'Roxo alegre e bem feminino de papel de embrulho.',
    'Cor de gominha de uva misturada com framboesa.',
  ]),
  colorHex('Ametista', '#9966CC', [
    'Roxo médio e suave com um toque de azul, a cor da pedra ametista.',
    'Mais calmo que a orquídea viva e mais claro que o violeta.',
    'Cor de cristal roxo de loja esotérica.',
    'Cor de colar de pedra de quem acredita em energia.',
    'Roxo de sombra de olho suave de manhã.',
  ]),
  colorHex('Lilás Forte', '#9370DB', [
    'Roxo médio e azulado, um lilás mais forte e mais cheio.',
    'Mais escuro que o lilás normal e mais claro que a ametista.',
    'Cor de camiseta lilás de show de banda de pop.',
    'Roxo de pétala de campânula num vaso de varanda.',
    'Cor de sofá moderno que quer ser alegre e elegante.',
  ]),
  colorHex('Violeta Azulado', '#8A2BE2', [
    'Roxo muito vivo e azulado, quase um azul que virou violeta.',
    'Mais forte que a ametista e mais azul que o violeta intenso.',
    'Cor de neon violeta de arcade de videogame.',
    'Cor de capa de super-herói misteriosa.',
    'Roxo de LED de teclado gamer em modo violeta.',
  ]),
  colorHex('Cardo', '#D8BFD8', [
    'Roxo bem claro e acinzentado, cor da flor do cardo seca.',
    'Mais cinza que o lilás e mais claro que a lavanda acinzentada.',
    'Cor de lençol de seda de hotel antigo.',
    'Roxo apagado de cortina de casa de campo.',
    'Cor de poeira de pétala caída no chão.',
  ]),
  colorHex('Ameixa Clara', '#DDA0DD', [
    'Rosa-roxo claro e suave, a polpa da ameixa clarinha.',
    'Mais rosado que o cardo e mais forte que o lilás.',
    'Cor de doce de ameixa cremoso em calda.',
    'Cor de esmalte clarinho de manicure delicada.',
    'Cor de brigadeiro de uva em festa de aniversário.',
  ]),
  colorHex('Violeta Claro', '#EE82EE', [
    'Rosa-roxo claro e alegre, a flor violeta de jardim bem iluminada.',
    'Mais claro e mais rosado que a orquídea viva.',
    'Cor de gominha de uva rosada de saquinho.',
    'Violeta de bolinha de borracha de brinquedo antigo.',
    'Cor de pelúcia de unicórnio de loja de brinquedo.',
  ]),
  colorHex('Uva Escura', '#4A235A', [
    'Roxo bem escuro, a cor da uva roxa quase preta, dessas de vinho.',
    'Mais escuro que o roxo uva e mais claro que a berinjela.',
    'Cor de veludo de poltrona de cinema antigo.',
    'Roxo de noite de tempestade distante.',
    'Cor de cortina pesada de teatro de ópera.',
  ]),
  colorHex('Jabuticaba', '#2B1631', [
    'Roxo muito escuro, quase preto, a casca da jabuticaba madura.',
    'Mais escuro que a berinjela, com um fundo roxo avermelhado.',
    'Cor de vinho tinto antes de a luz bater.',
    'Roxo de capa preta de vampiro elegante.',
    'Cor de fundo de apresentação gótica.',
  ]),
  colorHex('Lavanda Viva', '#7B68EE', [
    'Roxo azulado claro e vivo, cor de lavanda recém-colhida.',
    'Mais azul que o lilás e mais alegre que a ametista.',
    'Cor de camiseta de show de banda indie.',
    'Azul-violeta de céu de crepúsculo.',
    'Cor de luz de LED azul-arroxeada de quarto de adolescente.',
  ]),
  colorHex('Névoa Roxa', '#C3B1E1', [
    'Roxo claro e suave com tom azulado, uma névoa de lavanda no fim da tarde.',
    'Mais escuro que a lavanda e mais rosado que o azul lavanda.',
    'Cor de chá de ervas roxo no copo de vidro.',
    'Cor de cobertor de sofá em tom pastel.',
    'Cor de pétala de glicínia depois da chuva.',
  ]),
  colorHex('Rosa Pink', '#FF69B4', [
    'Rosa vivo e médio, a cor mais clássica do rosa chiclete de revista.',
    'Mais claro que o rosa choque e mais forte que o rosa chiclete.',
    'Cor de maquiagem de boneca, bem rosa e bem alegre.',
    'Rosa de flamingo de plástico de jardim.',
    'Cor de laço de cabelo de menina que adora rosa.',
  ]),
  colorHex('Violeta Rosado', '#C71585', [
    'Rosa forte e fundo com bastante roxo dentro, quase um magenta queimado.',
    'Mais escuro que o fúcsia e mais rosado que o magenta escuro.',
    'Cor de calda de framboesa com amora misturada.',
    'Cor de batom ousado de inverno.',
    'Rosa-roxo intenso de flor exótica.',
  ]),
  colorHex('Rosa Malva', '#DB7093', [
    'Rosa médio e meio apagado, com cara de rosa-velho.',
    'Mais fechado que o rosa chiclete e mais vivo que o rosa antigo.',
    'Cor de blusa vintage de feira de antiguidades.',
    'Cor de batom de dia, rosado e discreto.',
    'Cor de gominha de fruta vermelha misturada com leite.',
  ]),
  colorHex('Rosa Claro', '#FFB6C1', [
    'Rosa claro e suave, cor clássica de sorvete de morango bem leitoso.',
    'Mais pálido que o rosa pink e mais forte que o rosa bebê.',
    'Cor de laço rosa de embalagem de presente delicada.',
    'Rosa de gominha de bala mole de farmácia.',
    'Cor de bochecha com um blush leve.',
  ]),
  colorHex('Rosa Pálido', '#FFC0CB', [
    'Rosa bem clarinho e delicado, o rosa mais tradicional das lojas de bebê.',
    'Mais suave que o rosa claro, mais pálido que o rosa chiclete.',
    'Cor de roupinha de menina recém-nascida.',
    'Cor de sorvete de morango com muito leite.',
    'Rosa-ballet de sapatilha de dança nova.',
  ]),
  colorHex('Rosa Névoa', '#FFE4E1', [
    'Rosa quase branco, pálido, como uma névoa rosada em manhã de inverno.',
    'Mais claro que o rosa pálido, parecido com porcelana rosada.',
    'Cor de pétala de rosa branca iluminada pelo sol.',
    'Cor de glacê de bolo de casamento com um fio de rosa.',
    'Rosa de papel de embrulho caro, só um sopro de cor.',
  ]),
  colorHex('Pétala', '#FFF0F5', [
    'Branco com um sopro de rosa, quase sem cor, como pétala de flor branca.',
    'Mais pálido que o rosa névoa, parecendo papel de carta delicado.',
    'Cor de chantilly com uma gota de calda de morango.',
    'Cor de lençol de seda de cama de hotel romântico.',
    'Cor de renda branca de vestido de noiva, com luz rosada.',
  ]),
  colorHex('Rosa Tulipa', '#E75480', [
    'Rosa médio forte, um pouco escurecido, a pétala da tulipa rosa.',
    'Mais escuro que o rosa pink e mais vivo que o rosa malva.',
    'Cor de lábios com batom rosa forte.',
    'Cor de laço de presente de Dia das Mães.',
    'Rosa de camisa polo de verão de gente elegante.',
  ]),
  colorHex('Hibisco', '#D81B60', [
    'Rosa-vermelho forte, a cor da flor de hibisco aberta.',
    'Mais escuro que o rosa choque e mais rosado que a cereja.',
    'Cor de calda de frutas vermelhas bem concentrada.',
    'Rosa vibrante e meio vinho de camisa de time.',
    'Cor de batom de festa à noite.',
  ]),
  colorHex('Rosa Camélia', '#E91E63', [
    'Rosa forte e vivo, entre o pink e o vermelho, a pétala de camélia.',
    'Mais vermelho que o rosa choque, mais rosa que o carmim.',
    'Cor de capa de caderno de menina moderna.',
    'Cor de gominha de morango e framboesa.',
    'Rosa de bandeira de torcida organizada feminina.',
  ]),
  colorHex('Pitaya', '#E0245E', [
    'Rosa-avermelhado intenso, a casca vibrante da pitaya.',
    'Mais vermelho que o hibisco e mais aceso que a cereja.',
    'Cor de suco de frutas vermelhas bem forte.',
    'Rosa quente e exótico de cartaz de loja de sucos.',
    'Cor de bala de goma de morango azedinha.',
  ]),
  colorHex('Melancia', '#FC6C85', [
    'Rosa avermelhado claro e alegre, a polpa da melancia madura.',
    'Mais claro e mais alegre que o rosa tulipa.',
    'Cor de sorvete de melancia com raspas de chocolate.',
    'Rosa-vermelho de verão, com cara de piscina e fruta gelada.',
    'Cor de refresco de frutas vermelhas bem gelado.',
  ]),
  colorHex('Malva', '#915F6D', [
    'Rosa-roxo escuro e acinzentado, a cor da malva de jardim murcha.',
    'Mais apagado que o rosa antigo e mais fechado que a ameixa clara.',
    'Cor de poltrona antiga de casa de vó.',
    'Cor de cortina de seda de teatro pequeno.',
    'Cor de vinho misturado com leite, meio rosado e meio roxo.',
  ]),
  colorHex('Rosa Terroso', '#C4877E', [
    'Rosa avermelhado e terroso, a cor de barro rosado de louça artesanal.',
    'Mais alaranjado que o rosa antigo e mais claro que o terracota.',
    'Cor de tijolinho rosado de parede de casa de campo.',
    'Cor de batom nude em tom queimado.',
    'Rosa-barro de vaso grande de varanda.',
  ]),
  colorHex('Roxo Veludo', '#5B3A8C', [
    'Roxo escuro e azulado com cara de veludo de poltrona de teatro.',
    'Mais claro que a uva escura e mais azulado que o roxo uva.',
    'Cor de capa de livro de mistério sobre bruxos.',
    'Roxo de cortina pesada de teatro quando a luz está baixa.',
    'Cor de noite mágica de desenho animado.',
  ]),
  colorHex('Lavanda Acinzentada', '#B8A9C9', [
    'Roxo claro e acinzentado, cor da lavanda seca num pote de vidro.',
    'Mais cinza que o lilás e mais claro que o cardo.',
    'Cor de manhã de neblina em campo de lavanda.',
    'Cor de lã de ovelha tingida com ervas.',
    'Roxo apagado de capa de caderno elegante.',
  ]),
  colorHex('Malva Clara', '#D8B4E2', [
    'Roxo rosado claro e suave, a cor do lilás misturado com um fio de rosa.',
    'Mais claro que a orquídea e mais forte que o lilás pastel.',
    'Cor de glacê de cupcake de baunilha com corante.',
    'Cor de sabonete de lavanda com flores.',
    'Cor de laço de cabelo de menina em tom pastel.',
  ]),
];
