import { colorHex, type PaletteColor } from './palette-types';

/** Terras e metais, doces e comidas, frutas e flores. */
export const PALETTE_6: PaletteColor[] = [
  colorHex('Cobre', '#B87333', [
    'Laranja amarronzado e metálico, a cor da panela de cobre e do fio elétrico descascado.',
    'Mais alaranjado que o bronze e mais claro que o marrom couro.',
    'Cor de moeda de centavo velha.',
    'Cor de cano de cobre em casa antiga.',
    'Cor de cabelo ruivo-escuro de personagem de desenho.',
  ]),
  colorHex('Bronze', '#CD7F32', [
    'Laranja dourado amarronzado, a cor de medalha de bronze do terceiro lugar.',
    'Mais amarelo que o cobre e mais escuro que o caramelo.',
    'Cor de estátua antiga de praça pública.',
    'Cor de pele bem bronzeada depois de uma semana de praia.',
    'Cor de maçaneta de latão de porta de escritório.',
  ]),
  colorHex('Telha', '#C1583A', [
    'Laranja avermelhado e fosco, a cor da telha de barro de casa colonial.',
    'Mais vivo que o tijolo e mais escuro que o coral.',
    'Cor de telhado visto de cima numa cidade antiga.',
    'Cor de vaso de barro novo ainda sem terra dentro.',
    'Cor de pôr do sol em cidade do interior de Minas.',
  ]),
  colorHex('Canela', '#A65E2E', [
    'Marrom alaranjado médio, a cor da canela em pau e em pó.',
    'Mais claro que o marrom couro e mais quente que a madeira.',
    'Cor de biscoito de canela recém-assado.',
    'Cor de caneca de cerâmica artesanal.',
    'Cor de rolinho de canela com açúcar por cima.',
  ]),
  colorHex('Marrom Couro', '#8B4513', [
    'Marrom médio e quente, a cor do couro de sela de cavalo.',
    'Cor de sofá de couro bem usado e muito confortável.',
    'Mais escuro que o canela e mais alaranjado que o café.',
    'Cor de cinto e de botina de trabalho.',
    'Cor de porta de madeira de casa de fazenda.',
  ]),
  colorHex('Siena', '#A0522D', [
    'Marrom avermelhado e vivo, a cor do pigmento terra de Siena.',
    'Mais claro que o marrom couro, com um tom de ferrugem.',
    'Cor de barro vermelho molhado da estrada rural.',
    'Cor de tijolo queimado de forno artesanal.',
    'Cor de telhado antigo em dia de chuva.',
  ]),
  colorHex('Marrom Avermelhado', '#A52A2A', [
    'Marrom escuro com muito vermelho dentro, a cor da casca de tomate seco.',
    'Mais vermelho que o siena e mais vivo que o tijolo.',
    'Cor de tinta de armário de madeira de lei envernizado.',
    'Cor de mesa de bar antigo, bem escura e meio avermelhada.',
    'Marrom que parece vinho cozido em panela de barro.',
  ]),
  colorHex('Chocolate ao Leite', '#8B5A2B', [
    'Marrom médio e suave, a cor do chocolate ao leite em barra.',
    'Mais claro que o chocolate meio amargo e mais dourado que o café.',
    'Cor de calda de chocolate morna caindo no sorvete.',
    'Cor de brigadeiro quando acaba de sair da panela.',
    'Cor de casca de pão de forma bem dourada.',
  ]),
  colorHex('Marrom Dourado', '#CD853F', [
    'Marrom claro e alaranjado, a cor da madeira clara e do pão bem assado.',
    'Mais claro que o caramelo e mais quente que a duna.',
    'Cor de cabo de ferramenta de madeira polida.',
    'Cor de crosta de torta de maçã dourada.',
    'Cor de chapéu de palha de fazendeiro.',
  ]),
  colorHex('Areia Torrada', '#F4A460', [
    'Laranja claro e terroso, a cor da areia aquecida pelo sol do meio-dia.',
    'Mais claro que o marrom dourado e mais alaranjado que a duna.',
    'Cor de doce de abóbora com coco.',
    'Cor de pele bronzeada com filtro dourado.',
    'Cor de biscoito de polvilho tostadinho.',
  ]),
  colorHex('Ocre', '#CC7722', [
    'Amarelo alaranjado e terroso, a cor do pigmento de argila ocre.',
    'Mais escuro e mais fosco que a cúrcuma, mais claro que a ferrugem.',
    'Cor de parede pintada em tom de campo do Mediterrâneo.',
    'Cor de pintura rupestre em caverna antiga.',
    'Cor de folha de outono no chão de uma praça.',
  ]),
  colorHex('Barro', '#A1664A', [
    'Marrom avermelhado e fosco, a cor do barro seco de vaso artesanal.',
    'Mais claro que o siena e mais rosado que a madeira.',
    'Cor de casinha de pau a pique em cidade do interior.',
    'Cor de panela de barro capixaba de moqueca.',
    'Cor de tijolo aparente rústico em parede de pizzaria.',
  ]),
  colorHex('Argila', '#B66A50', [
    'Laranja-marrom rosado e fosco, a cor da argila vermelha de escultura.',
    'Mais claro e mais rosado que o barro, mais escuro que o terracota.',
    'Cor de vaso de cerâmica de loja de decoração.',
    'Cor de parede de casa de campo em tom quente.',
    'Cor de potinho de planta de cacto fofo.',
  ]),
  colorHex('Siena Queimada', '#8A3324', [
    'Marrom avermelhado escuro, a cor do pigmento de terra queimada.',
    'Mais escuro que o siena, quase um vinho amarronzado.',
    'Cor de tijolo bem queimado de lareira antiga.',
    'Cor de móvel de mogno vermelho escuro.',
    'Cor de molho de pimenta que já ferveu demais.',
  ]),
  colorHex('Noz', '#5C4033', [
    'Marrom escuro e acinzentado, a cor da casca da noz.',
    'Mais claro que a trufa e mais apagado que o café.',
    'Cor de móvel escuro de escritório antigo.',
    'Cor de bota de couro velha depois de uma trilha.',
    'Cor de café com leite quase sem leite.',
  ]),
  colorHex('Trufa', '#3D2B1F', [
    'Marrom muito escuro, quase preto, a cor da trufa de chocolate cortada ao meio.',
    'Mais escuro que a noz e mais quente que o grafite.',
    'Cor de grão de café muito torrado.',
    'Cor de terra molhada depois da chuva.',
    'Marrom de brigadeiro de cacau puro.',
  ]),
  colorHex('Mogno', '#4D1F10', [
    'Marrom muito escuro e avermelhado, a cor da madeira mogno polida.',
    'Mais vermelho que a trufa e mais fechado que o siena queimada.',
    'Cor de piano de cauda em sala de concerto antiga.',
    'Cor de gaveta de móvel de herança de família.',
    'Cor de cacau puro em pó antes de misturar.',
  ]),
  colorHex('Amêndoa', '#EFDECD', [
    'Bege rosado muito claro, a cor da amêndoa descascada.',
    'Mais claro e mais quente que o bege, quase um creme com rosa.',
    'Cor de glacê de doce de amêndoas.',
    'Cor de parede de quarto em tom neutro e acolhedor.',
    'Cor de biscoito de amêndoa antes de entrar no forno.',
  ]),
  colorHex('Camurça', '#C19A6B', [
    'Marrom suave e macio, a cor do couro de camurça de sapato.',
    'Mais dourado que a duna e mais escuro que a madeira clara.',
    'Cor de sofá de camurça em sala de estar.',
    'Cor de botina de couro macio de cowboy.',
    'Cor de bolsa de couro de loja de acessórios.',
  ]),
  colorHex('Biscoito', '#E4C590', [
    'Bege dourado e claro, a cor de biscoito de polvilho recém-saído do forno.',
    'Mais amarelado que a duna e mais claro que a camurça.',
    'Cor de casca de pão de queijo ainda quentinho.',
    'Cor de farinha de trigo torrada para o roux.',
    'Cor de torrada de pão branco bem dourada.',
  ]),
  colorHex('Madeira Clara', '#DEB887', [
    'Marrom claro e dourado, a cor da madeira de pinus polida.',
    'Mais claro que o marrom dourado e mais amarelado que a duna.',
    'Cor de mesa de madeira de cozinha de casa de campo.',
    'Cor de tábua de cortar pão em padaria.',
    'Cor de piso de madeira clara em apartamento moderno.',
  ]),
  colorHex('Duna', '#D2B48C', [
    'Bege queimado e quente, a cor da areia de duna no deserto.',
    'Mais claro que a camurça e mais marrom que o bege.',
    'Cor de papel pardo de embrulho de padaria.',
    'Cor de sandália de couro cru de verão.',
    'Cor de sofá de linho em decoração rústica.',
  ]),
  colorHex('Rapadura', '#9B6A3C', [
    'Marrom dourado e escuro, a cor do bloco de rapadura com melado.',
    'Mais claro que o chocolate e mais quente que a noz.',
    'Cor de doce de leite cozido por muito tempo.',
    'Cor de açúcar mascavo em pote de vidro.',
    'Cor de cuia de chimarrão bem curada.',
  ]),
  colorHex('Doce de Leite', '#C69C6D', [
    'Marrom claro e cremoso, a cor do doce de leite pastoso na colher.',
    'Mais claro que a rapadura e mais amarelado que o café com leite.',
    'Cor de recheio de alfajor aberto.',
    'Cor de calda de caramelo já morna.',
    'Cor de casca de coxinha bem dourada.',
  ]),
  colorHex('Pão de Mel', '#7A4B2A', [
    'Marrom médio e escuro, a cor da casquinha do pão de mel coberta de chocolate.',
    'Mais claro que a noz e mais quente que o chocolate.',
    'Cor de bolo de mel e especiarias de festa junina.',
    'Cor de gengibre assado em padaria artesanal.',
    'Cor de panela de ferro bem curada.',
  ]),
  colorHex('Paçoca', '#C9A27A', [
    'Bege queimado e arenoso, a cor da paçoca de amendoim esfarelada.',
    'Mais claro e mais seco que o doce de leite.',
    'Cor de farofa de carne seca bem dourada.',
    'Cor de farinha de mandioca torrada.',
    'Cor de saco de aniagem de feira.',
  ]),
  colorHex('Fubá', '#F7D774', [
    'Amarelo claro e quente, a cor do fubá de milho na tigela de bolo.',
    'Mais claro que o açafrão e mais amarelo que o creme.',
    'Cor de farinha de milho antes de virar angu.',
    'Cor de bolo de milho cremoso cortado ao meio.',
    'Cor de canjica cozida e servida quente.',
  ]),
  colorHex('Farinha', '#EADBC0', [
    'Bege amarelado muito claro, a cor da farinha de trigo integral.',
    'Mais claro que a duna e mais amarelado que o osso.',
    'Cor de massa de pão antes de crescer.',
    'Cor de sacola de papel de padaria em dia ensolarado.',
    'Cor de tapioca hidratada ainda crua.',
  ]),
  colorHex('Terra de Sombra', '#5C4B37', [
    'Marrom escuro e acinzentado, a cor da terra de sombra de pintor.',
    'Mais claro que a trufa, com um fundo oliva e apagado.',
    'Cor de casca de árvore velha em tronco molhado.',
    'Cor de tinta de aquarela de paisagem de outono.',
    'Cor de solo da floresta depois de um tempo sem chuva.',
  ]),
  colorHex('Sépia', '#704214', [
    'Marrom escuro alaranjado e envelhecido, a cor das fotografias antigas.',
    'Mais claro que o mogno, com um tom de papel amarelado.',
    'Cor de tinta de caneta-tinteiro marrom de diário.',
    'Cor de mapa velho do tempo dos descobrimentos.',
    'Cor de carta de amor escondida em gaveta.',
  ]),
  colorHex('Ocre Claro', '#DDB26F', [
    'Amarelo amarronzado claro, a cor de argila ocre seca ao sol.',
    'Mais claro que o ocre e mais amarelado que a madeira clara.',
    'Cor de parede de casa em país do Mediterrâneo.',
    'Cor de pão italiano com casquinha dourada.',
    'Cor de saco de trigo moído na roça.',
  ]),
  colorHex('Lichia', '#F5C6C6', [
    'Rosa bem clarinho e suave, a cor da polpa da lichia e da casca clara.',
    'Mais pálido que o rosa pálido e mais acinzentado.',
    'Cor de sorvete de lichia com um fio de calda.',
    'Cor de sabonete de rosas de bairro antigo.',
    'Cor de esmalte clarinho de pele suave.',
  ]),
  colorHex('Pitanga', '#D0312D', [
    'Vermelho forte e vivo, a cor da pitanga madura no pé.',
    'Mais claro que a cereja e mais vermelho que a romã.',
    'Cor de bala de cereja vermelha de fabricante famoso.',
    'Cor de acerola bem madura no pé.',
    'Cor de gominha de morango bem forte.',
  ]),
  colorHex('Jaca', '#E9C46A', [
    'Amarelo dourado e suave, a cor do bago da jaca madura.',
    'Mais claro que o ouro e mais apagado que o amarelo táxi.',
    'Cor de doce de abóbora cremoso com coco.',
    'Cor de pele de mamão formosa madura.',
    'Cor de fruta tropical amassada num suco denso.',
  ]),
  colorHex('Carambola', '#E6D84C', [
    'Amarelo esverdeado e vivo, a cor da carambola madura cortada em estrela.',
    'Mais esverdeado que o amarelo limão e mais claro que a mostarda.',
    'Cor de gominha de abacaxi com um toque de limão.',
    'Cor de sol filtrado por folhas verdes.',
    'Cor de fita de cetim amarelo-esverdeada de presente.',
  ]),
  colorHex('Ipê Amarelo', '#FFD21F', [
    'Amarelo forte e luminoso, a cor das flores do ipê amarelo na primavera.',
    'Mais claro que o ouro e mais forte que o amarelo banana.',
    'Cor de tapete de flores caídas em calçada de cidade.',
    'Cor de bandeirinha de festa junina vista de longe.',
    'Cor de camiseta de seleção em dia de decisão.',
  ]),
  colorHex('Ipê Roxo', '#B07CC6', [
    'Roxo médio e rosado, a cor das flores do ipê roxo na rua.',
    'Mais claro que o roxo uva e mais rosado que a ametista.',
    'Cor de copa de árvore florida em avenida arborizada.',
    'Cor de gominha de uva misturada com rosa.',
    'Cor de pétala caída depois do vento forte.',
  ]),
  colorHex('Ipê Rosa', '#E58AB5', [
    'Rosa médio e suave, a cor das flores do ipê rosa em agosto.',
    'Mais forte que o rosa claro e mais suave que o rosa pink.',
    'Cor de laço de presente em papel fosco.',
    'Cor de pétala rosa espalhada pela calçada depois do vento.',
    'Cor de copa de árvore toda florida em rua de bairro.',
  ]),
  colorHex('Flamboyant', '#E2431F', [
    'Vermelho alaranjado vivo, a cor das flores do flamboyant ao sol.',
    'Mais claro e mais laranja que o vermelho de bombeiro.',
    'Cor de copa de árvore em chamas num verão forte.',
    'Cor de brasa suave de churrasqueira.',
    'Cor de brasa de lenha que acabou de pegar.',
  ]),
  colorHex('Jacarandá', '#9B8AC4', [
    'Roxo azulado e suave, a cor das flores do jacarandá em cachos.',
    'Mais claro que a ametista e mais azulado que a orquídea.',
    'Cor de tapete de pétalas roxas em calçada de primavera.',
    'Cor de véu de neblina em campo de lavanda.',
    'Roxo de sombra de olho num dia de festa.',
  ]),
  colorHex('Buganvília', '#D6336C', [
    'Rosa-vermelho forte e vibrante, a cor das flores de buganvília no muro.',
    'Mais avermelhado que o rosa choque e mais rosado que o hibisco.',
    'Cor de cerca viva toda florida em casa de praia.',
    'Cor de gominha de morango misturada com framboesa.',
    'Cor de laço de presente de Natal em tom rosa forte.',
  ]),
  colorHex('Margarida', '#FFF6B3', [
    'Amarelo bem claro e suave, o miolo da margarida aberta no jardim.',
    'Mais claro e mais suave que o amarelo banana.',
    'Cor de glacê de limão com leite condensado.',
    'Cor de gema de ovo cozida bem clara.',
    'Cor de lençol de bebê em tom manteiga.',
  ]),
];
