import { color, colorHex, type PaletteColor } from './palette-types';

/** Azuis e turquesas, do gelo ao azul da meia-noite. */
export const PALETTE_5: PaletteColor[] = [
  color('Turquesa', 175, 80, 85, [
    'Azul-esverdeado vivo e alegre, cor da água de praia de cartão-postal.',
    'Metade azul, metade verde, e nenhuma das duas cede.',
    'Cor da pedra turquesa de colar de feira de artesanato.',
    'Mais verde que o azul piscina e mais azul que o verde água.',
    'Cor de tênis de corrida que você usa e esquece de lavar.',
  ]),
  color('Ciano', 180, 100, 100, [
    'Azul-esverdeado puro e luminoso, o ciano da impressora, sem enfeites.',
    'Exatamente no meio entre o verde e o azul.',
    'Cor da tinta do cartucho que sempre acaba na hora errada.',
    'Cor do céu de videogame antigo, daquele sem textura nenhuma.',
    'Fresco, elétrico e sem nenhum tom de cinza.',
  ]),
  color('Azul Piscina', 190, 70, 95, [
    'Azul claro e vivo com um fio de verde, a cor da piscina limpa em dia de calor.',
    'Cor de toalha de piscina de clube que ninguém devolve.',
    'Mais esverdeado que o céu e mais azul que o turquesa.',
    'Azul de bala de goma azeda que você chupa fazendo careta.',
    'Cor de boia de pato quando está muito cheia.',
  ]),
  color('Azul Céu', 205, 55, 98, [
    'Azul claro e aberto, a cor do céu de dia bonito, sem nuvem nenhuma.',
    'Cor de céu de desenho de criança, aquele em que o sol usa óculos.',
    'Mais forte que o azul bebê e mais leve que o azul royal.',
    'Cor da camisa social azul que todo mundo tem no armário.',
    'Cor de balão de gás solto em festa de formatura.',
  ]),
  color('Azul Bebê', 205, 25, 100, [
    'Azul clarinho e delicado, cor de roupinha de bebê.',
    'Quase branco com uma pitada de céu.',
    'Cor de chupeta de enxoval que combina com tudo.',
    'Cor de algodão-doce quando o rosa acabou.',
    'Azul de quarto de criança montado com muito amor e muito pastel.',
  ]),
  color('Azul Gelo', 195, 18, 98, [
    'Branco com um sopro azul, cor de gelo recém-saído do congelador.',
    'Quase não tem cor: é um azul tão claro que parece reflexo.',
    'Cor de pista de patinação vista de cima.',
    'Cor de geleira em foto de folheto de viagem.',
    'Mais branco que o azul bebê e bem mais frio.',
  ]),
  color('Azul Jeans', 215, 65, 60, [
    'Azul médio e acinzentado, a cor da calça jeans de uso diário.',
    'Cor de mochila escolar que sobreviveu a três anos de aula.',
    'Mais escuro que o azul céu e mais claro que o marinho.',
    'Cor de jaqueta jeans esquecida no encosto da cadeira.',
    'Parece desbotado de propósito, e de propósito é caro.',
  ]),
  color('Azul Royal', 225, 85, 80, [
    'Azul forte e profundo, o azul de manto de rei em quadro de museu.',
    'Cor do uniforme de time que tem muita torcida.',
    'Mais profundo que o céu e mais vivo que o marinho.',
    'O azul da caneta esferográfica quando você assina o contrato.',
    'Azul vibrante e elegante ao mesmo tempo, sem nada de cinza.',
  ]),
  color('Azul Elétrico', 235, 90, 100, [
    'Azul fortíssimo com um toque de violeta, parece que tomou um choque.',
    'Cor de luz de teclado gamer que o vizinho deixa ligada.',
    'Mais violeta que o royal e bem mais aceso.',
    'Azul de raio em desenho de super-herói.',
    'Forte demais para ser calmo, bonito demais para ser ignorado.',
  ]),
  color('Azul Marinho', 220, 85, 35, [
    'Azul bem escuro, de uniforme de marinheiro e de blazer de reunião.',
    'Quase preto, mas com um fundo azul profundo quando a luz bate.',
    'A cor da calça social que combina com tudo.',
    'Mais escuro que o jeans e menos preto que a meia-noite.',
    'Cor de capa de passaporte de país sério.',
  ]),
  color('Azul Petróleo', 195, 85, 40, [
    'Azul-esverdeado escuro e fundo, cor de lago profundo em dia de chuva.',
    'Mais verde que o marinho e mais escuro que o turquesa.',
    'Cor de poltrona de veludo de restaurante discreto.',
    'Cor de capa de livro de ficção científica dos anos oitenta.',
    'Misturinha de azul e verde que ficou séria demais.',
  ]),
  color('Azul Cobalto', 215, 100, 70, [
    'Azul intenso e puro, o azul de pigmento de pintor a óleo.',
    'Cor de vidro de farmácia antiga que ninguém joga fora.',
    'Mais vivo que o jeans e mais escuro que o royal.',
    'Azul de azulejo que enfeita fachada de igreja portuguesa.',
    'Forte, sólido e sem uma gota de cinza.',
  ]),
  color('Azul Anil', 235, 75, 55, [
    'Azul escuro com um toque de roxo, o anil dos tecidos tingidos à mão.',
    'Cor do céu na hora em que escurece, antes das estrelas.',
    'Entre o azul marinho e o violeta, mais perto do azul.',
    'Cor de calça de brim que desbotou do jeito certo.',
    'Cor de tinta de caneta-tinteiro depois de secar.',
  ]),
  color('Azul Noite', 230, 70, 25, [
    'Quase preto, com um azul bem fundo escondido lá dentro.',
    'A cor do céu às duas da manhã sem lua.',
    'Mais escuro que o marinho e mais azulado que o grafite.',
    'Cor de veludo de caixa de joia.',
    'Se o preto tivesse um sonho azul, seria esse.',
  ]),
  colorHex('Azul Puro', '#0000FF', [
    'O azul mais azul que existe, forte e escuro, sem nenhum tom de verde ou roxo.',
    'Cor de link clicado em página antiga da internet.',
    'Azul de caneta Bic azul, só que muito mais aceso.',
    'Mais forte que o royal e mais puro que o elétrico.',
    'Cor da tela azul de computador quando dá erro.',
  ]),
  colorHex('Azul Profundo', '#00008B', [
    'Azul escuro e puro, com muito corpo, bem mais fechado que o royal.',
    'Cor do fundo do oceano visto em desenho de livro.',
    'Mais vivo que o marinho e sem nenhum cinza.',
    'Cor de uniforme de time tradicional, azul sério.',
    'Cor de capa de livro de direito, pesada e respeitável.',
  ]),
  colorHex('Meia-Noite', '#191970', [
    'Azul escuro com um toque de roxo, a cor do céu à meia-noite.',
    'Mais violeta que o marinho e mais claro que o azul noite.',
    'Cor de veludo de cortina de teatro, do lado da plateia.',
    'Azul de blazer chique de jantar de gala.',
    'Cor de tinta de caneta de luxo, bem azul-escura.',
  ]),
  colorHex('Azul Aço', '#4682B4', [
    'Azul médio e um pouco acinzentado, a cor do aço de ferramenta vista ao sol.',
    'Mais calmo que o jeans e mais claro que o petróleo.',
    'Cor de ponte de ferro vista de longe, em dia nublado.',
    'Azul de blusa polo de executivo em reunião de segunda.',
    'Cor de capa de computador portátil que parece cara.',
  ]),
  colorHex('Azul Cadete', '#5F9EA0', [
    'Azul esverdeado e acinzentado, tipo mar de dia de vento fraco.',
    'Cor de uniforme de cadete de escola militar.',
    'Mais cinza que o turquesa e mais claro que o petróleo.',
    'Azul de lagoa em foto antiga com filtro suave.',
    'Cor de parede de clínica que quer passar tranquilidade.',
  ]),
  colorHex('Azul Clarinho', '#ADD8E6', [
    'Azul claro e suave, a cor do céu de manhã bem cedo.',
    'Mais claro e mais calmo que o azul céu.',
    'Cor de camiseta lavada muitas vezes, já desbotada.',
    'Azul de iogurte de mirtilo com leite.',
    'Cor de balão azul-claro que ninguém lembra de estourar.',
  ]),
  colorHex('Azul Pó', '#B0E0E6', [
    'Azul claro e esverdeado, parecido com água limpa de piscina rasa.',
    'Cor de pó de maquiagem azulado, tipo sombra de olho suave.',
    'Mais esverdeado que o azul clarinho e mais pálido que o piscina.',
    'Cor de louça de porcelana azul-clara em cozinha de avó.',
    'Azul de geladeira antiga restaurada em tom vintage.',
  ]),
  colorHex('Aço Claro', '#B0C4DE', [
    'Azul acinzentado bem claro, cor de metal polido com um reflexo de céu.',
    'Mais cinza que o azul pó, com um jeito de nuvem.',
    'Cor de ardósia clara numa tarde nublada.',
    'Azul de jeans lavado com água sanitária.',
    'Cor de capa de agenda de escritório com cara de elegante.',
  ]),
  colorHex('Azul Celeste', '#00BFFF', [
    'Azul claro e muito vivo, cor de céu tropical em foto sem filtro.',
    'Mais forte que o azul céu e mais claro que o azul vivo.',
    'Cor de piscina de resort em propaganda de viagem.',
    'Azul de gomas ácidas de sabor "blue ice".',
    'Cor da luz de LED de teclado que o vizinho usa em tom azul-claro.',
  ]),
  colorHex('Azul Vivo', '#1E90FF', [
    'Azul médio e muito vivo, daqueles que parecem acesos por dentro.',
    'Cor de ícone de rede social de mensagem azul.',
    'Mais claro que o royal e mais forte que o azul céu.',
    'Cor de tinta de caneta esferográfica de ponta grossa.',
    'Azul de camisa de time que chama atenção na arquibancada.',
  ]),
  colorHex('Centáurea', '#6495ED', [
    'Azul médio e suave com um toque de violeta, a flor centáurea no campo.',
    'Mais calmo que o azul vivo e mais claro que o jeans.',
    'Cor de camiseta polo de domingo de clube.',
    'Azul de cobertor de sofá em tarde fria.',
    'Cor de rótulo de produto de higiene de supermercado.',
  ]),
  colorHex('Azul Oceano', '#006994', [
    'Azul escuro esverdeado, a cor do oceano profundo longe da praia.',
    'Mais fechado que o azul aço e mais claro que o azul marinho.',
    'Azul de documentário sobre baleias.',
    'Cor de capa de livro sobre o mar e navegação.',
    'Cor de uniforme de marinheiro de navio mercante.',
  ]),
  colorHex('Azul Caribe', '#1CA9C9', [
    'Azul claro esverdeado e vivo, a cor do mar do Caribe em folheto de agência.',
    'Mais verde que o céu e mais forte que o azul piscina.',
    'Cor de calça de verão em tom de turquesa-azulado.',
    'Cor de coquetel azul com guarda-chuvinha.',
    'Azul de boia de piscina que dá vontade de pular dentro.',
  ]),
  colorHex('Hortênsia', '#8EA4D2', [
    'Azul claro e suave com um fundo de violeta, cor de flor de hortênsia azul.',
    'Mais calmo que a centáurea e mais claro que o azul jeans.',
    'Azul de blusa de lã de bebê, delicado e meio acinzentado.',
    'Cor de ramo de flores em vaso de cerâmica no balcão da padaria.',
    'Azul suave com um toque de lavanda, bem florido.',
  ]),
  colorHex('Safira', '#0F52BA', [
    'Azul profundo e intenso, cor da pedra safira em anel de noiva.',
    'Mais claro que o cobalto e mais vivo que o jeans.',
    'Cor de vestido azul de gala sob a luz do salão.',
    'Azul vibrante e elegante, de joia de verdade.',
    'Azul de bandeirinha de time clássico na arquibancada.',
  ]),
  colorHex('Pavão', '#0A7E8C', [
    'Azul-esverdeado escuro, cor do peito do pavão aberto ao sol.',
    'Mais verde que o petróleo e mais escuro que o turquesa.',
    'Cor de tecido de sofá de veludo azul-esverdeado de restaurante chique.',
    'Cor de azulejo de cozinha em tom oceano.',
    'Azul de lago profundo e protegido do vento.',
  ]),
  colorHex('Turquesa Clara', '#AFEEEE', [
    'Azul-esverdeado clarinho e pálido, a cor da água de lago raso.',
    'Cor de bala de chiclete sabor menta com gelo.',
    'Mais pálido que o turquesa e mais esverdeado que o azul pó.',
    'Cor de espuma de sabonete de piscina cheia de bolhas.',
    'Azul pastel esverdeado de parede de quarto de bebê.',
  ]),
  colorHex('Turquesa Viva', '#00CED1', [
    'Azul-esverdeado vivo e luminoso, cor de piscina de resort em foto turística.',
    'Mais claro que o turquesa e mais verde que o ciano.',
    'Cor de sorvete de menta com chiclete azul.',
    'Azul de mar de praia deserta em tela de computador.',
    'Cor de lanterna de LED que parece de brinquedo.',
  ]),
  colorHex('Azul Tiffany', '#81D8D0', [
    'Azul-esverdeado claro e delicado, a cor da caixinha de joalheria famosa.',
    'Mais pálido que o turquesa e mais suave que o ciano.',
    'Cor de lacinho de presente de aniversário chique.',
    'Azul de azulejo de piscina antiga em clube de elite.',
    'Cor de esmalte de manicure que combina com tudo.',
  ]),
  colorHex('Verde Azulado', '#008080', [
    'Verde-azulado escuro e firme, a cor de pato selvagem na água parada.',
    'Mais escuro que o turquesa e mais verde que o azul petróleo.',
    'Cor de chapéu de feltro verde-azulado de um clube de golfe.',
    'Cor de capa de livro de ficção científica dos anos setenta.',
    'Azul de gaveta de móvel antigo pintado a mão.',
  ]),
  colorHex('Ciano Escuro', '#008B8B', [
    'Azul-esverdeado escuro e puro, bem fechado, sem nenhum cinza.',
    'Mais escuro que o ciano e mais verde que o petróleo.',
    'Cor de tinta de impressora velha, quase acabando.',
    'Cor de lagoa funda vista de um barco.',
    'Cor de azulejo de banheiro dos anos sessenta.',
  ]),
  colorHex('Azul Prússia', '#003153', [
    'Azul muito escuro e meio esverdeado, o azul-da-prússia de tinta de pintor.',
    'Mais escuro que o petróleo e mais acinzentado que a meia-noite.',
    'Cor de fundo de mar à noite em desenho técnico.',
    'Azul de gravata de executivo muito sério.',
    'Cor de tinteiro de nanquim azul, quase preto.',
  ]),
  colorHex('Azul Lavanda', '#B4C5E4', [
    'Azul claro e suave com um toque de lilás, cor de flor de lavanda azulada.',
    'Mais violeta que o azul clarinho e mais cinza que o céu.',
    'Cor de lençol de algodão pastel de cama de menina.',
    'Azul de sombra de olho pastel de manhã.',
    'Cor de véu de neblina de montanha ao amanhecer.',
  ]),
  colorHex('Denim', '#1560BD', [
    'Azul forte e profundo, a cor do denim de calça jeans nova, ainda sem lavar.',
    'Mais vivo que o jeans e mais claro que o cobalto.',
    'Azul de camiseta de empresa de tecnologia.',
    'Cor de caneca esmaltada de acampamento.',
    'Azul de boné de time tradicional.',
  ]),
  colorHex('Azul Mar Profundo', '#003F5C', [
    'Azul escuro e esverdeado, a cor da água do mar bem longe da costa.',
    'Mais escuro que o petróleo e mais frio que o marinho.',
    'Cor de submarino em desenho animado.',
    'Cor de capa de relatório de empresa de petróleo.',
    'Azul de tinta de lousa de escola antiga.',
  ]),
  colorHex('Azul Tinta', '#1B2A49', [
    'Azul bem escuro e acinzentado, a cor da tinta azul-marinho de caneta-tinteiro.',
    'Mais escuro que o marinho e mais frio que o grafite.',
    'Cor de uniforme de piloto de avião.',
    'Azul de capa de livro de capa dura e papel grosso.',
    'Cor de terno cinza-azulado de advogado respeitado.',
  ]),
  colorHex('Azul Fumê', '#5A6E8C', [
    'Azul acinzentado médio, a cor do vidro escuro de janela de carro.',
    'Mais cinza que o jeans e mais escuro que o azul aço.',
    'Cor de nuvem de chuva carregada, vista de longe.',
    'Azul de blusa de moletom que já foi lavada mil vezes.',
    'Cor de capa de celular que combina com tudo e não chama atenção.',
  ]),
  colorHex('Azul Porcelana', '#A9CCE3', [
    'Azul claro e suave com um toque de cinza, a cor da porcelana azul de prato antigo.',
    'Mais acinzentado que o azul clarinho e mais pálido que o aço.',
    'Cor de xícara de chá que a avó só usa em visita.',
    'Azul de caixa de remédio em embalagem de farmácia.',
    'Azul de papel de parede florido de quarto de hóspedes.',
  ]),
  colorHex('Azul Polar', '#D6EAF8', [
    'Azul bem pálido, quase branco com um fundo de gelo, a cor do ártico.',
    'Mais claro que o azul gelo, com um pouquinho mais de cor.',
    'Cor de neve vista sob luz azulada de inverno.',
    'Azul de lençol de hospital em dia de sol.',
    'Cor de pasta de dente de gel clarinha.',
  ]),
  colorHex('Azul Maré', '#2F6F8F', [
    'Azul médio e esverdeado, a cor do mar na maré cheia em dia nublado.',
    'Mais claro que o azul oceano e mais acinzentado que o petróleo.',
    'Azul de lago de montanha onde ninguém ousa nadar.',
    'Azul de capa de livro de poesia náutica.',
    'Cor de camisa de pescador depois de um dia no sol.',
  ]),
  colorHex('Azul Vidro', '#A5D8E6', [
    'Azul claro e transparente, a cor do vidro de garrafa azul-clara contra a luz.',
    'Cor de gelo de supermercado em saquinho.',
    'Mais esverdeado que o azul clarinho e mais vivo que o pó.',
    'Azul de bolinha de gude de coleção de criança.',
    'Cor de água de piscina rasa vista de cima.',
  ]),
  colorHex('Azul Sereno', '#7AA6C2', [
    'Azul médio e suave, um azul calmo de lago em dia sem vento.',
    'Mais acinzentado que o céu e mais claro que o aço.',
    'Cor de parede de consultório que tenta passar paz.',
    'Cor de camiseta de linho azul de verão.',
    'Azul de capa de caderno de bem-estar.',
  ]),
  colorHex('Azul Bandeira', '#002776', [
    'O azul-escuro do círculo da bandeira do Brasil, forte e profundo.',
    'Mais escuro e mais puro que o azul royal.',
    'Azul de farda de cadete e de camisa de seleção reserva.',
    'Cor do globo da bandeira nacional no céu da noite.',
    'Azul de pano de bandeira pendurada em estádio.',
  ]),
];
