import { color, type PaletteColor } from './palette-types';

/** Frios: verdes e azuis. */
export const PALETTE_2: PaletteColor[] = [
  color('Verde Folha', 120, 70, 65, [
    'O verde de folha de árvore em dia comum: nem neon, nem escuro, simplesmente verde.',
    'Cor de alface que passou do ponto de ser salada e virou paisagem.',
    'Verde equilibrado, sem nenhum tom de amarelo ou de azul puxando para os lados.',
    'Cor de gramado de praça bem cuidada, daquele em que ninguém pode pisar.',
    'Brilho médio-alto e saturação boa: é um verde que respira.',
    'Metade do caminho entre o verde limão e o verde floresta.',
    'A cor das folhas da planta que você jura que vai regar amanhã.',
    'Cor de couve crua ainda inteira: verde firme, sem brilho de neon.',
    'Pense em horta de avó: couve, cheiro-verde e esse tom em todo lugar.',
  ]),
  color('Verde Limão', 80, 85, 95, [
    'Verde com muito amarelo por dentro, o verde do limão quando ainda não amadureceu.',
    'Cor de bala azeda que faz careta antes mesmo de você mastigar.',
    'Quase fluorescente, mas ainda com cara de fruta cortada na hora.',
    'Brilho altíssimo e muito amarelado: é o verde a um passo do amarelo.',
    'A cor do marca-texto verde, aquele que acaba antes de qualquer outro.',
    'Cor de raspa de limão ralada em cima da caipirinha.',
    'Verde que dá vontade de espremer: fresco, ácido e cheio de energia.',
    'Mais claro e mais amarelo que uma folha; mais ácido que uma maçã verde.',
    'Se o verde tomasse café forte e ficasse agitado, seria assim.',
  ]),
  color('Verde Neon', 110, 80, 100, [
    'Verde que brilha no escuro, pelo menos na sua imaginação.',
    'Brilho no máximo e saturação lá em cima: é verde de letreiro de loja de conveniência.',
    'Cor de pulseira de show que ainda acende às três da manhã.',
    'Tão forte que dói olhar: nada de pastel, nada de sombra.',
    'A cor do slime que a sobrinha jura que é de brinquedo.',
    'Verde de substância radioativa de desenho animado, daquelas que escorrem do barril.',
    'Cor de raio laser de apresentação de empresa que quer parecer moderna.',
    'Mais vivo que a grama e mais verde que a ervilha: pura energia sem controle.',
    'Se tivesse som, seria um zumbido agudo e feliz.',
  ]),
  color('Verde Maçã', 95, 70, 85, [
    'A casca da maçã verde bem lavada, meio amarelada e bem crocante.',
    'Cor de bala de maçã verde que sempre sobra no pote.',
    'Verde claro com tom de limão, mas mais calmo que o verde limão.',
    'Brilho alto, saturação média-alta: fresco sem agredir.',
    'A cor da gelatina de maçã verde balançando no prato.',
    'Entre o limão e a folha, mas puxando para o lado da fruta.',
    'Dá para sentir o azedinho só de olhar.',
    'Pense numa maçã na fruteira que ninguém quer comer porque é azeda, mas é linda.',
    'Verde de embalagem de chiclete que promete sabor natural e não cumpre.',
  ]),
  color('Verde Pistache', 85, 35, 90, [
    'Sorvete de pistache derretendo devagar: verde claro, cremoso e meio acinzentado.',
    'Bem suave, com pouca saturação: o verde que não quer chamar atenção.',
    'Verde de macaron francês que custa o triplo do que deveria.',
    'Mais amarelo que a menta, menos vivo que a lima.',
    'Cor de parede de consultório de dentista: calma e um pouco antiga.',
    'Brilho alto e saturação baixa: pastel puxando para o amarelado.',
    'A cor da casca do pistache depois de aberto.',
    'Parece um verde que tomou banho de leite.',
    'Cor de geladeira retrô dos anos cinquenta.',
  ]),
  color('Verde Menta', 150, 30, 95, [
    'Verde clarinho e fresco, com um toque azulado, como bala de menta.',
    'A cor do chiclete que promete hálito de montanha.',
    'Pasta de dente em gel bem aberta: pastel e gelada.',
    'Mais azulado que o pistache e mais claro que o jade.',
    'Cor de sabonete de hotel que você leva na mala sem culpa.',
    'Brilho altíssimo e saturação baixa: parece um verde lavado em água gelada.',
    'A cor do picolé de menta com pedacinhos de chocolate.',
    'Se um dia gelado virasse cor, seria essa.',
    'Verde de balão de festa infantil de bom gosto.',
  ]),
  color('Verde Floresta', 140, 80, 35, [
    'Verde bem escuro, de floresta fechada onde o sol mal entra.',
    'Cor de mesa de bilhar, só que mais fundo e mais sério.',
    'Brilho baixíssimo: quase preto, mas ainda dá para jurar que é verde.',
    'A cor dos pinheiros vistos de longe à noite.',
    'Verde de livro antigo de capa dura na estante do escritório.',
    'Cor de cortina de teatro de bairro: pesada e discreta.',
    'Pinheiro de Natal depois de apagar as luzinhas.',
    'Escuro e frio: nada de amarelo, só mato fechado.',
    'O verde do bosque dos contos em que alguém sempre se perde.',
  ]),
  color('Verde Musgo', 80, 60, 45, [
    'Verde acinzentado e escuro, cor de pedra úmida coberta de musgo.',
    'Puxa para o amarelo e para o marrom, como folha de outono que ainda não caiu.',
    'Cor de roupa militar discreta, daquelas de acampamento.',
    'Brilho médio-baixo e saturação média: terroso, nunca vibrante.',
    'A cor da parede do banheiro externo que ninguém limpa.',
    'Verde de sapo velho, daqueles com pose de sábio.',
    'Cor de pântano em dia nublado.',
    'Mais escuro e mais opaco que a folha, mais claro que o preto.',
    'A cor de uma barraca de camping herdada de um parente distante.',
  ]),
  color('Verde Oliva', 65, 70, 50, [
    'A cor da azeitona verde, do caroço à casca.',
    'Verde amarelado e escuro, daquele que lembra uniforme do exército.',
    'Cor de lata de conserva esquecida no fundo do armário.',
    'Brilho médio-baixo e muito amarelo no meio: é o verde que quase virou marrom.',
    'A cor do azeite quando a luz bate de lado na garrafa.',
    'Verde de jaqueta de caçador sem muito entusiasmo.',
    'Parece sujo, mas de um jeito chique.',
    'Mais amarelo que o musgo, mais sério que a maçã.',
    'Cor de mochila tática que alguém comprou e nunca levou a lugar nenhum.',
  ]),
  color('Verde Esmeralda', 150, 85, 75, [
    'Verde de joia de verdade: profundo, vivo e levemente azulado.',
    'A cor das pedras dos anéis que a rainha usa no retrato.',
    'Brilho alto e saturação bem alta: é um verde rico, quase luxuoso.',
    'Cor da mata atlântica vista de helicóptero.',
    'Mais frio que a folha, mais claro que a floresta.',
    'O verde do trevo de quatro folhas de quem tem muita sorte.',
    'Cor de vestido de gala que ninguém usa duas vezes.',
    'Intenso, brilhante e com um pé no azul.',
    'Parece uma floresta que ganhou holofote.',
  ]),
  color('Verde Bandeira', 144, 100, 61, [
    'O verde da bandeira do Brasil: forte, escuro e cheio de orgulho.',
    'Cor da camisa da seleção vista de longe no gramado.',
    'Saturação no máximo e brilho médio: nada de pastel aqui.',
    'Verde de campo de futebol visto na televisão antiga.',
    'Mais escuro que a esmeralda e sem aquele ar de joia.',
    'A cor que aparece em todo dia de Copa do Mundo, em tudo.',
    'Verde grave e firme, como quem vai cantar o hino.',
    'Cor de pano de bandeira pendurado na janela do vizinho.',
    'Se o Brasil fosse um giz de cera, esse seria o primeiro a acabar.',
  ]),
  color('Verde Abacate', 78, 55, 70, [
    'A polpa do abacate no ponto: verde amarelado, macio e cremoso.',
    'Cor de guacamole que alguém deixou sem limão e escureceu um pouquinho.',
    'Verde claro com amarelo, mas mais apagado que o limão.',
    'Brilho médio-alto, saturação média: um verde que dá fome.',
    'A cor do creme de abacate com açúcar da sobremesa da avó.',
    'Cor de sofá retrô dos anos setenta que voltou à moda.',
    'Mais suave que a maçã e mais quente que a menta.',
    'Cor da torrada de abacate das fotos de café da manhã chique.',
    'Verde que parece macio só de olhar.',
  ]),
  color('Verde Jade', 160, 60, 65, [
    'Verde-azulado de pedra de jade polida, calma e antiga.',
    'Cor de colar que a tia tirou da caixinha para o casamento.',
    'Frio e profundo, mas sem a energia da esmeralda.',
    'Brilho médio e saturação média: um verde com pé no azul.',
    'A cor do chá verde quando ainda não ficou forte demais.',
    'Cor de estatueta de escritório de quem faz ioga todo dia.',
    'Mais azul que a folha e mais acinzentado que a esmeralda.',
    'Verde de lago de montanha onde você não ousa nadar.',
    'Cor de louça chinesa que ninguém pode quebrar.',
  ]),
  color('Verde Água', 165, 45, 85, [
    'O verde clarinho da água de piscina com um toque de verde-azulado.',
    'Cor de aquário limpo com plantinhas.',
    'Entre a menta e o turquesa, mas bem suave e calmo.',
    'Brilho alto, saturação média-baixa: um verde com cara de praia tranquila.',
    'A cor da água do mar caribenho em foto de agência de viagem.',
    'Cor de bala de hortelã dentro do pote de vidro.',
    'Mais azul que a menta, mais verde que o azul piscina.',
    'Parece um verde que está de férias.',
    'Cor de parede de banheiro que quer parecer spa.',
  ]),
  color('Turquesa', 175, 80, 85, [
    'Azul-esverdeado vivo, como a água de uma praia de cartão-postal.',
    'A cor da pedra que a vendedora de feira jura que traz sorte.',
    'Metade azul, metade verde, e nenhuma delas cede.',
    'Brilho alto e saturação forte: alegre como piscina em dia de calor.',
    'Cor de tênis de corrida que você usa e esquece de lavar.',
    'A cor do mar onde o barco vira estrela de foto.',
    'Mais verde que o azul piscina e mais azul que o verde água.',
    'Parece uma gelatina de sabor fantasia.',
    'Cor de capa de caderno que sempre acaba na papelaria.',
  ]),
  color('Ciano', 180, 100, 100, [
    'Azul-esverdeado puro, o ciano da impressora, sem enfeites.',
    'A cor da tinta do cartucho que sempre acaba na hora errada.',
    'Saturação e brilho no máximo: brilhante como tela de celular.',
    'Exatamente no meio entre verde e azul no círculo de cores.',
    'Cor do céu de videogame antigo, daquele sem textura nenhuma.',
    'A cor do refrigerante azul de que ninguém lembra o sabor.',
    'Fresco, elétrico e sem nenhum tom de cinza.',
    'Cor de neon de lanchonete americana nos filmes.',
    'Se o gelo tivesse luz própria, seria esse.',
  ]),
  color('Azul Piscina', 190, 70, 95, [
    'O azul da piscina limpa, cheia de cloro e cheia de criança.',
    'Azul claro com um fio de verde, cor de dia de verão.',
    'Brilho altíssimo e saturação alta: parece refrescar só de olhar.',
    'Cor de toalha de piscina de clube que ninguém devolve.',
    'Mais esverdeado que o céu e mais azul que o turquesa.',
    'A cor da água de uma propaganda de sabonete.',
    'Azul de bala de goma ácida que você chupa fazendo careta.',
    'Cor de boia de pato quando está muito, muito cheia.',
    'Vontade de pular dentro: esse é o tom.',
  ]),
  color('Azul Céu', 205, 55, 98, [
    'O azul do céu de dia bonito, sem nuvem nenhuma.',
    'Cor de céu de desenho de criança, aquele em que o sol usa óculos.',
    'Brilho altíssimo, saturação média: azul claro e aberto.',
    'Mais forte que o azul bebê e mais leve que o azul royal.',
    'A cor da camisa social azul que todo mundo tem no armário.',
    'Cor de balão de gás lançado em festa de formatura.',
    'Azul de manhã tranquila de domingo.',
    'Parece o fundo de uma tela de computador antiga.',
    'A cor que o céu tem nas fotos que ninguém precisa filtrar.',
  ]),
  color('Azul Bebê', 205, 25, 100, [
    'Azul clarinho de roupinha de bebê, bem delicado e sem graça de propósito.',
    'Quase branco com uma pitada de céu.',
    'Brilho máximo e saturação baixa: um azul fofo e macio.',
    'Cor de chupeta de enxoval que combina com tudo.',
    'Mais claro e mais suave que o azul céu.',
    'Cor de algodão-doce quando o rosa acabou.',
    'Azul de quarto de criança montado com muito amor e muito pastel.',
    'Parece nuvem vista de cima por uma criança.',
    'Pense num azul que pede desculpas antes de aparecer.',
  ]),
  color('Azul Gelo', 195, 18, 98, [
    'Branco com um sopro azul, cor de gelo recém-saído do congelador.',
    'Quase não tem cor: é um azul tão claro que parece reflexo.',
    'Brilho altíssimo, saturação baixíssima: frio e transparente.',
    'Cor de pista de patinação vista de cima.',
    'Cor de geleira em foto de folheto de viagem.',
    'Mais branco que o azul bebê e bem mais frio.',
    'Cor de lençol de hospital novo.',
    'Se um suspiro congelasse, seria essa cor.',
    'Cor da tampa de iogurte desnatado.',
  ]),
  color('Azul Jeans', 215, 65, 60, [
    'O azul da calça jeans de uso diário, meio lavado e muito confortável.',
    'Azul médio e acinzentado, cor de roupa que já viu muita coisa.',
    'Brilho médio, saturação média: nem claro, nem escuro.',
    'Cor de mochila escolar que sobreviveu a três anos de aula.',
    'Mais escuro que o céu e mais claro que o marinho.',
    'A cor da camisa de botão que você usa até gastar.',
    'Cor de jaqueta jeans esquecida no encosto da cadeira.',
    'Azul de macacão de trabalho em dia de domingo.',
    'Parece desbotado de propósito, e de propósito é caro.',
  ]),
  color('Azul Royal', 225, 85, 80, [
    'Azul forte e nobre, de manto de rei em quadro de museu.',
    'Brilho alto e saturação alta, sem nenhum cinza.',
    'Cor do uniforme de time que tem muita torcida.',
    'Mais profundo que o céu e mais vivo que o marinho.',
    'Cor de tapete de escada de teatro importante.',
    'O azul da caneta esferográfica quando você assina o contrato.',
    'Azul vibrante e elegante ao mesmo tempo.',
    'Cor de seda de lenço de quem anda de limusine.',
    'Se o azul precisasse de coroa, usaria essa.',
  ]),
  color('Azul Elétrico', 235, 90, 100, [
    'Azul que parece ter tomado um choque: vibrante, quase violeta.',
    'Cor de faísca de tomada com defeito (não teste em casa).',
    'Brilho no máximo e saturação lá em cima: é azul de letreiro.',
    'Mais violeta que o royal e bem mais aceso.',
    'Azul de tela de erro de computador de antigamente.',
    'Cor de luz de teclado gamer que o vizinho deixa ligada.',
    'Parece tinta que brilha mesmo sem luz.',
    'Azul de raio em desenho de super-herói.',
    'Forte demais para ser calmo, bonito demais para ser ignorado.',
  ]),
  color('Azul Marinho', 220, 85, 35, [
    'Azul bem escuro, de uniforme de marinheiro e de blazer de reunião.',
    'Quase preto, mas com um fundo azul profundo quando a luz bate.',
    'Brilho baixo e saturação alta: sério, discreto e elegante.',
    'A cor da calça social que combina com tudo.',
    'Cor do mar à noite visto da janela do navio.',
    'Azul de capa de passaporte de país sério.',
    'Mais escuro que o jeans e menos preto que a meia-noite.',
    'Cor de terno do primeiro emprego.',
    'Parece azul que foi dormir cedo.',
  ]),
  color('Azul Petróleo', 195, 85, 40, [
    'Azul-esverdeado bem escuro, de óleo no fundo do poço.',
    'Cor de parede de sala chique decorada por quem entende.',
    'Brilho baixo e saturação alta, com um fundo verde bem forte.',
    'Mais verde que o marinho e mais escuro que o turquesa.',
    'A cor da cadeira de veludo de restaurante discreto.',
    'Azul de lago profundo em dia de chuva.',
    'Cor de capa de livro de ficção científica dos anos oitenta.',
    'Cor de sofá que ninguém tem coragem de pôr perto do cachorro.',
    'Misturinha de azul e verde que ficou séria demais.',
  ]),
  color('Azul Cobalto', 215, 100, 70, [
    'Azul intenso e puro, cor de pigmento de pintor a óleo.',
    'Cor de vidro de farmácia antiga que ninguém joga fora.',
    'Saturação no máximo e brilho médio-alto: um azul concentrado.',
    'Mais vivo que o jeans e mais escuro que o royal.',
    'A cor de cerâmica pintada à mão de Portugal.',
    'Azul de azulejo que enfeita fachada de igreja.',
    'Cor de tinta que o artista guarda para a obra principal.',
    'Forte, sólido e sem uma gota de cinza.',
    'Parece azul de verdade, daquele que o resto tenta imitar.',
  ]),
  color('Azul Anil', 235, 75, 55, [
    'Azul escuro com um toque roxo, o anil dos tecidos tingidos à mão.',
    'Cor de céu na hora em que escurece, antes das estrelas.',
    'Brilho médio-baixo e saturação alta: profundo e meio sonhador.',
    'Entre o marinho e o violeta, mais perto do azul.',
    'Cor de calça de brim que desbotou do jeito certo.',
    'O azul do cantinho da lavanderia de antigamente.',
    'Cor de tinta de caneta-tinteiro depois de secar.',
    'Mais roxo que o marinho e mais frio que o jeans.',
    'Parece uma noite com cara de início de história.',
  ]),
  color('Azul Noite', 230, 70, 25, [
    'Quase preto, com um azul bem fundo escondido lá dentro.',
    'A cor do céu às duas da manhã sem lua.',
    'Brilho baixíssimo: só dá para ver que é azul se você prestar atenção.',
    'Mais escuro que o marinho, mais azulado que o grafite.',
    'Cor de capa de livro de mistério que cheira a biblioteca.',
    'Se o preto tivesse um sonho azul, seria esse.',
    'Cor de tela desligada com um toque de reflexo.',
    'Azul de veludo de caixa de joia.',
    'Cor de fundo de apresentação que quer parecer elegante.',
  ]),
];
